
//=========oOOOo===========================================oOOOo==========
//  Verilog file generated by HqFpga(TM) v3.0.3 (Winter 2023) Build 021824
//  Time : Sat Feb 24 01:11:20 2024

//  Xian Intelligence Silicon Technology, Inc.(XiST)
//========================================================================
	

// work.top(top)
module top
(
    clk_27M,
    clk_25M,
    clk_p3,
    clk_p4,
    clk_p5,
    flash_miso,
    swdclk,
    key_pin,
    uart_DAP_rx,
    uart_ch340_rx,
    sd_miso,
    w5500_rstn,
    w5500_intn,
    w5500_miso,
    led_core,
    pll_i2c_scl,
    SRAM_ADDR,
    SRAM_nWE,
    SRAM_nOE,
    SRAM_nCE,
    SRAM_nLB,
    SRAM_nUB,
    flash_sclk,
    flash_cs,
    flash_mosi,
    led_pin,
    beep_pin,
    uart_DAP_tx,
    uart_ch340_tx,
    sd_sclk,
    sd_cs,
    sd_mosi,
    w5500_sclk,
    w5500_cs,
    w5500_mosi,
    seg7_SH_CP,
    seg7_ST_CP,
    seg7_DS,
    i2c_scl,
    osc_c6_pin,
    pll_i2c_sda,
    SRAM_DQ,
    swddio,
    i2c_sda
);
    input  clk_27M;
    input  clk_25M;
    input  clk_p3;
    input  clk_p4;
    input  clk_p5;
    input  flash_miso;
    input  swdclk;
    input  [2:0] key_pin;
    input  uart_DAP_rx;
    input  uart_ch340_rx;
    input  sd_miso;
    input  w5500_rstn;
    input  w5500_intn;
    input  w5500_miso;
    output led_core;
    output pll_i2c_scl;
    output [18:0] SRAM_ADDR;
    output SRAM_nWE;
    output SRAM_nOE;
    output SRAM_nCE;
    output SRAM_nLB;
    output SRAM_nUB;
    output flash_sclk;
    output flash_cs;
    output flash_mosi;
    output [3:0] led_pin;
    output beep_pin;
    output uart_DAP_tx;
    output uart_ch340_tx;
    output sd_sclk;
    output sd_cs;
    output sd_mosi;
    output w5500_sclk;
    output w5500_cs;
    output w5500_mosi;
    output seg7_SH_CP;
    output seg7_ST_CP;
    output seg7_DS;
    output i2c_scl;
    output osc_c6_pin;
    inout  pll_i2c_sda;
    inout  [15:0] SRAM_DQ;
    inout  swddio;
    inout  i2c_sda;
    wire \cm3inst/TMSO ;
    wire \cm3inst/TMSOEN ;
    wire clk_25M_c;
    wire swdclk_c;
    wire \key_pin[0]_c ;
    wire uart_DAP_rx_c;
    wire \led_pin[1]_c ;
    wire uart_DAP_tx_c;
    wire n_VCC_c;
    wire n_GND_c;
    wire osc_c6_pin_c;
    wire _n_0_combout;

    xsCM3 \cm3inst/inst 
    (
        .DBG_SWDI_TMS(_n_0_combout),
        .CS_TCK(swdclk_c),
        .CIBCLK(clk_25M_c),
        .CPURSTN(\key_pin[0]_c ),
        .INITEXP0HMASTLOCK(n_GND_c),
        .INITEXP0HSEL(n_GND_c),
        .INITEXP0HWRITE(n_GND_c),
        .INITEXP1HMASTLOCK(n_GND_c),
        .INITEXP1HSEL(n_GND_c),
        .INITEXP1HWRITE(n_GND_c),
        .MTXRSTN(\key_pin[0]_c ),
        .NSRST(n_VCC_c),
        .NTRST(n_VCC_c),
        .TREECLK(clk_25M_c),
        .DBG_SWDO(\cm3inst/TMSO ),
        .DBG_SWDO_EN(\cm3inst/TMSOEN ),
        .INITEXP1HBURST({3{n_GND_c}}),
        .INITEXP1HSIZE({3{n_GND_c}}),
        .GPIOI({{29{n_GND_c}}, uart_DAP_rx_c, {2{n_GND_c}}}),
        .INITEXP0HSIZE({3{n_GND_c}}),
        .INITEXP0HBURST({3{n_GND_c}}),
        .GPIOO({HQSYN__DUMMY__0, HQSYN__DUMMY__1, HQSYN__DUMMY__2, HQSYN__DUMMY__3, HQSYN__DUMMY__4, HQSYN__DUMMY__5, HQSYN__DUMMY__6, HQSYN__DUMMY__7, HQSYN__DUMMY__8, HQSYN__DUMMY__9, HQSYN__DUMMY__10, HQSYN__DUMMY__11, HQSYN__DUMMY__12, HQSYN__DUMMY__13, HQSYN__DUMMY__14, HQSYN__DUMMY__15, HQSYN__DUMMY__16, HQSYN__DUMMY__17, HQSYN__DUMMY__18, HQSYN__DUMMY__19, HQSYN__DUMMY__20, HQSYN__DUMMY__21, HQSYN__DUMMY__22, HQSYN__DUMMY__23, HQSYN__DUMMY__24, HQSYN__DUMMY__25, HQSYN__DUMMY__26, HQSYN__DUMMY__27, uart_DAP_tx_c, HQSYN__DUMMY__28, \led_pin[1]_c , osc_c6_pin_c}),
        .DMACBREQ({4{n_GND_c}}),
        .INITEXP1HWDATA({32{n_GND_c}}),
        .DMACLBREQ({4{n_GND_c}}),
        .DMACSREQ({4{n_GND_c}}),
        .DMACLSREQ({4{n_GND_c}}),
        .INITEXP1HADDR({32{n_GND_c}}),
        .INITEXP0HWDATA({32{n_GND_c}}),
        .INITEXP0HADDR({32{n_GND_c}}),
        .INITEXP1HPROT({4{n_GND_c}}),
        .EXTINT({16{n_GND_c}}),
        .INITEXP0HPROT({4{n_GND_c}}),
        .INITEXP1HTRANS({2{n_GND_c}}),
        .INITEXP0HTRANS({2{n_GND_c}})
    );
    defparam \cm3inst/inst .CORECLK = "CLK_TREE";
    defparam \cm3inst/inst .CORECLK_EN = "TRUE";
    defparam \cm3inst/inst .CORE_SET = "TRUE";
    defparam \cm3inst/inst .MTXCLK = "CORECLK";
    defparam \cm3inst/inst .PCLK_DIV = 0;
    defparam \cm3inst/inst .RSTN_ENABLE = "TRUE";

    xsIOBI clk_25M_pad
    (
        .I(clk_25M),
        .O(clk_25M_c)
    );
    xsIOBI swdclk_pad
    (
        .I(swdclk),
        .O(swdclk_c)
    );
    xsIOBI \key_pin[0]_pad 
    (
        .I(key_pin[0]),
        .O(\key_pin[0]_c )
    );
    xsIOBI uart_DAP_rx_pad
    (
        .I(uart_DAP_rx),
        .O(uart_DAP_rx_c)
    );
    xsIOBO led_core_pad
    (
        .I(n_GND_c),
        .O(led_core)
    );
    xsIOBO \SRAM_ADDR[18]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[18])
    );
    xsIOBO \SRAM_ADDR[17]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[17])
    );
    xsIOBO \SRAM_ADDR[16]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[16])
    );
    xsIOBO \SRAM_ADDR[15]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[15])
    );
    xsIOBO \SRAM_ADDR[14]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[14])
    );
    xsIOBO \SRAM_ADDR[13]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[13])
    );
    xsIOBO \SRAM_ADDR[12]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[12])
    );
    xsIOBO \SRAM_ADDR[11]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[11])
    );
    xsIOBO \SRAM_ADDR[10]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[10])
    );
    xsIOBO \SRAM_ADDR[9]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[9])
    );
    xsIOBO \SRAM_ADDR[8]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[8])
    );
    xsIOBO \SRAM_ADDR[7]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[7])
    );
    xsIOBO \SRAM_ADDR[6]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[6])
    );
    xsIOBO \SRAM_ADDR[5]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[5])
    );
    xsIOBO \SRAM_ADDR[4]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[4])
    );
    xsIOBO \SRAM_ADDR[3]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[3])
    );
    xsIOBO \SRAM_ADDR[2]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[2])
    );
    xsIOBO \SRAM_ADDR[1]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[1])
    );
    xsIOBO \SRAM_ADDR[0]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[0])
    );
    xsIOBO SRAM_nWE_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nWE)
    );
    xsIOBO SRAM_nOE_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nOE)
    );
    xsIOBO SRAM_nCE_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nCE)
    );
    xsIOBO SRAM_nLB_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nLB)
    );
    xsIOBO SRAM_nUB_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nUB)
    );
    xsIOBO flash_sclk_pad
    (
        .I(n_GND_c),
        .O(flash_sclk)
    );
    xsIOBO flash_cs_pad
    (
        .I(n_VCC_c),
        .O(flash_cs)
    );
    xsIOBO flash_mosi_pad
    (
        .I(n_GND_c),
        .O(flash_mosi)
    );
    xsIOBO \led_pin[3]_pad 
    (
        .I(n_GND_c),
        .O(led_pin[3])
    );
    xsIOBO \led_pin[2]_pad 
    (
        .I(n_GND_c),
        .O(led_pin[2])
    );
    xsIOBO \led_pin[1]_pad 
    (
        .I(\led_pin[1]_c ),
        .O(led_pin[1])
    );
    xsIOBO \led_pin[0]_pad 
    (
        .I(osc_c6_pin_c),
        .O(led_pin[0])
    );
    xsIOBO beep_pin_pad
    (
        .I(n_GND_c),
        .O(beep_pin)
    );
    xsIOBO uart_DAP_tx_pad
    (
        .I(uart_DAP_tx_c),
        .O(uart_DAP_tx)
    );
    xsIOBO uart_ch340_tx_pad
    (
        .I(n_GND_c),
        .O(uart_ch340_tx)
    );
    xsIOBO sd_sclk_pad
    (
        .I(n_GND_c),
        .O(sd_sclk)
    );
    xsIOBO sd_cs_pad
    (
        .I(n_VCC_c),
        .O(sd_cs)
    );
    xsIOBO sd_mosi_pad
    (
        .I(n_GND_c),
        .O(sd_mosi)
    );
    xsIOBO w5500_sclk_pad
    (
        .I(n_GND_c),
        .O(w5500_sclk)
    );
    xsIOBO w5500_cs_pad
    (
        .I(n_VCC_c),
        .O(w5500_cs)
    );
    xsIOBO w5500_mosi_pad
    (
        .I(n_GND_c),
        .O(w5500_mosi)
    );
    xsIOBO seg7_SH_CP_pad
    (
        .I(n_GND_c),
        .O(seg7_SH_CP)
    );
    xsIOBO seg7_ST_CP_pad
    (
        .I(n_VCC_c),
        .O(seg7_ST_CP)
    );
    xsIOBO seg7_DS_pad
    (
        .I(n_GND_c),
        .O(seg7_DS)
    );
    xsIOBO osc_c6_pin_pad
    (
        .I(osc_c6_pin_c),
        .O(osc_c6_pin)
    );
    xsIOBB swddio_pad
    (
        .I(\cm3inst/TMSO ),
        .T(\cm3inst/TMSOEN ),
        .O(_n_0_combout),
        .B(swddio)
    );
    xs0 _i_4
    (
        .G(n_GND_c)
    );
    xs1 _i_3
    (
        .P(n_VCC_c)
    );


endmodule
