
//=========oOOOo===========================================oOOOo==========
//  Verilog file generated by HqFpga(TM) v2.14.4 (Winter 2023) Build 021824
//  Time : Sat Feb 24 15:30:14 2024

//  Xian Intelligence Silicon Technology, Inc.(XiST)
//========================================================================
	

// work.top(top)
module top
(
    clk_27M,
    clk_25M,
    clk_p3,
    clk_p4,
    clk_p5,
    flash_miso,
    swdclk,
    key_pin,
    uart_DAP_rx,
    uart_ch340_rx,
    sd_miso,
    w5500_rstn,
    w5500_intn,
    w5500_miso,
    led_core,
    pll_i2c_scl,
    SRAM_ADDR,
    SRAM_nWE,
    SRAM_nOE,
    SRAM_nCE,
    SRAM_nLB,
    SRAM_nUB,
    flash_sclk,
    flash_cs,
    flash_mosi,
    led_pin,
    beep_pin,
    uart_DAP_tx,
    uart_ch340_tx,
    sd_sclk,
    sd_cs,
    sd_mosi,
    w5500_sclk,
    w5500_cs,
    w5500_mosi,
    seg7_SH_CP,
    seg7_ST_CP,
    seg7_DS,
    i2c_scl,
    osc_c6_pin,
    pll_i2c_sda,
    SRAM_DQ,
    swddio,
    i2c_sda
);
    input  clk_27M;
    input  clk_25M;
    input  clk_p3;
    input  clk_p4;
    input  clk_p5;
    input  flash_miso;
    input  swdclk;
    input  [2:0] key_pin;
    input  uart_DAP_rx;
    input  uart_ch340_rx;
    input  sd_miso;
    input  w5500_rstn;
    input  w5500_intn;
    input  w5500_miso;
    output led_core;
    output pll_i2c_scl;
    output [18:0] SRAM_ADDR;
    output SRAM_nWE;
    output SRAM_nOE;
    output SRAM_nCE;
    output SRAM_nLB;
    output SRAM_nUB;
    output flash_sclk;
    output flash_cs;
    output flash_mosi;
    output [3:0] led_pin;
    output beep_pin;
    output uart_DAP_tx;
    output uart_ch340_tx;
    output sd_sclk;
    output sd_cs;
    output sd_mosi;
    output w5500_sclk;
    output w5500_cs;
    output w5500_mosi;
    output seg7_SH_CP;
    output seg7_ST_CP;
    output seg7_DS;
    output i2c_scl;
    output osc_c6_pin;
    inout  pll_i2c_sda;
    inout  [15:0] SRAM_DQ;
    inout  swddio;
    inout  i2c_sda;
    wire clk_200M;
    wire \led_wf1/n_3 ;
    wire [23:0] \led_wf1/cnt ;
    wire \led_wf1/n_11 ;
    wire \led_wf1/n_12 ;
    wire \led_wf1/n_13 ;
    wire \led_wf1/n_14 ;
    wire \led_wf1/n_15 ;
    wire \led_wf1/n_16 ;
    wire \led_wf1/n_17 ;
    wire \led_wf1/n_18 ;
    wire \led_wf1/n_19 ;
    wire \led_wf1/n_20 ;
    wire \led_wf1/n_21 ;
    wire \led_wf1/n_22 ;
    wire \led_wf1/n_23 ;
    wire \led_wf1/n_24 ;
    wire \led_wf1/n_25 ;
    wire \led_wf1/n_26 ;
    wire \led_wf1/n_27 ;
    wire \led_wf1/n_28 ;
    wire \led_wf1/n_29 ;
    wire \led_wf1/n_30 ;
    wire \led_wf1/n_31 ;
    wire \led_wf1/n_32 ;
    wire \led_wf1/n_33 ;
    wire \led_wf1/n_34 ;
    wire \cm3inst/TMSO ;
    wire \cm3inst/TMSOEN ;
    wire \PLL_25to200_1/CLKINTFB_t ;
    wire \led_wf1/n_35[1] ;
    wire \led_wf1/_i_6/_n_1 ;
    wire \led_wf1/n_35[2] ;
    wire \led_wf1/_i_6/_n_3 ;
    wire \led_wf1/n_35[3] ;
    wire \led_wf1/_i_6/_n_5 ;
    wire \led_wf1/n_35[4] ;
    wire \led_wf1/_i_6/_n_7 ;
    wire \led_wf1/n_35[5] ;
    wire \led_wf1/_i_6/_n_9 ;
    wire \led_wf1/n_35[6] ;
    wire \led_wf1/_i_6/_n_11 ;
    wire \led_wf1/n_35[7] ;
    wire \led_wf1/_i_6/_n_13 ;
    wire \led_wf1/n_35[8] ;
    wire \led_wf1/_i_6/_n_15 ;
    wire \led_wf1/n_35[9] ;
    wire \led_wf1/_i_6/_n_17 ;
    wire \led_wf1/n_35[10] ;
    wire \led_wf1/_i_6/_n_19 ;
    wire \led_wf1/n_35[11] ;
    wire \led_wf1/_i_6/_n_21 ;
    wire \led_wf1/n_35[12] ;
    wire \led_wf1/_i_6/_n_23 ;
    wire \led_wf1/n_35[13] ;
    wire \led_wf1/_i_6/_n_25 ;
    wire \led_wf1/n_35[14] ;
    wire \led_wf1/_i_6/_n_27 ;
    wire \led_wf1/n_35[15] ;
    wire \led_wf1/_i_6/_n_29 ;
    wire \led_wf1/n_35[16] ;
    wire \led_wf1/_i_6/_n_31 ;
    wire \led_wf1/n_35[17] ;
    wire \led_wf1/_i_6/_n_33 ;
    wire \led_wf1/n_35[18] ;
    wire \led_wf1/_i_6/_n_35 ;
    wire \led_wf1/n_35[19] ;
    wire \led_wf1/_i_6/_n_37 ;
    wire \led_wf1/n_35[20] ;
    wire \led_wf1/_i_6/_n_39 ;
    wire \led_wf1/n_35[21] ;
    wire \led_wf1/_i_6/_n_41 ;
    wire \led_wf1/n_35[22] ;
    wire \led_wf1/_i_6/_n_43 ;
    wire \led_wf1/n_35[23] ;
    wire \led_wf1/_i_2/_i_0_rkd_12 ;
    wire \led_wf1/_i_2/_i_0_rkd_14 ;
    wire \led_wf1/_i_2/_i_0_rkd_16 ;
    wire \led_wf1/_i_2/_i_0_rkd_19 ;
    wire _n_140;
    wire _n_141;
    wire clk_25M_c;
    wire swdclk_c;
    wire \key_pin[1]_c ;
    wire \key_pin[0]_c ;
    wire uart_DAP_rx_c;
    wire led_core_c;
    wire \led_pin[3]_c ;
    wire \led_pin[2]_c ;
    wire \led_pin[1]_c ;
    wire beep_pin_c;
    wire uart_DAP_tx_c;
    wire n_VCC_c;
    wire n_GND_c;
    wire osc_c6_pin_c;
    wire _n_142_combout;

    xsCM3 \cm3inst/inst 
    (
        .DBG_SWDI_TMS(_n_142_combout),
        .CS_TCK(swdclk_c),
        .CIBCLK(clk_200M),
        .CPURSTN(\key_pin[0]_c ),
        .INITEXP0HMASTLOCK(n_GND_c),
        .INITEXP0HSEL(n_GND_c),
        .INITEXP0HWRITE(n_GND_c),
        .INITEXP1HMASTLOCK(n_GND_c),
        .INITEXP1HSEL(n_GND_c),
        .INITEXP1HWRITE(n_GND_c),
        .MTXRSTN(\key_pin[0]_c ),
        .NSRST(n_VCC_c),
        .NTRST(n_VCC_c),
        .TREECLK(clk_200M),
        .DBG_SWDO(\cm3inst/TMSO ),
        .DBG_SWDO_EN(\cm3inst/TMSOEN ),
        .INITEXP1HBURST({3{n_GND_c}}),
        .INITEXP1HSIZE({3{n_GND_c}}),
        .GPIOI({{29{n_GND_c}}, uart_DAP_rx_c, {2{n_GND_c}}}),
        .INITEXP0HSIZE({3{n_GND_c}}),
        .INITEXP0HBURST({3{n_GND_c}}),
        .GPIOO({HQSYN__DUMMY__0, HQSYN__DUMMY__1, HQSYN__DUMMY__2, HQSYN__DUMMY__3, HQSYN__DUMMY__4, HQSYN__DUMMY__5, HQSYN__DUMMY__6, HQSYN__DUMMY__7, HQSYN__DUMMY__8, HQSYN__DUMMY__9, HQSYN__DUMMY__10, HQSYN__DUMMY__11, HQSYN__DUMMY__12, HQSYN__DUMMY__13, HQSYN__DUMMY__14, HQSYN__DUMMY__15, HQSYN__DUMMY__16, HQSYN__DUMMY__17, HQSYN__DUMMY__18, HQSYN__DUMMY__19, HQSYN__DUMMY__20, HQSYN__DUMMY__21, HQSYN__DUMMY__22, HQSYN__DUMMY__23, HQSYN__DUMMY__24, HQSYN__DUMMY__25, HQSYN__DUMMY__26, HQSYN__DUMMY__27, uart_DAP_tx_c, HQSYN__DUMMY__28, beep_pin_c, led_core_c}),
        .DMACBREQ({4{n_GND_c}}),
        .INITEXP1HWDATA({32{n_GND_c}}),
        .DMACLBREQ({4{n_GND_c}}),
        .DMACSREQ({4{n_GND_c}}),
        .DMACLSREQ({4{n_GND_c}}),
        .INITEXP1HADDR({32{n_GND_c}}),
        .INITEXP0HWDATA({32{n_GND_c}}),
        .INITEXP0HADDR({32{n_GND_c}}),
        .INITEXP1HPROT({4{n_GND_c}}),
        .EXTINT({16{n_GND_c}}),
        .INITEXP0HPROT({4{n_GND_c}}),
        .INITEXP1HTRANS({2{n_GND_c}}),
        .INITEXP0HTRANS({2{n_GND_c}})
    );
    defparam \cm3inst/inst .CORECLK = "CIB_CLK";
    defparam \cm3inst/inst .CORECLK_EN = "TRUE";
    defparam \cm3inst/inst .CORE_SET = "TRUE";
    defparam \cm3inst/inst .MTXCLK = "CORECLK";
    defparam \cm3inst/inst .PCLK_DIV = 0;
    defparam \cm3inst/inst .RSTN_ENABLE = "TRUE";

    xsPLLSA \PLL_25to200_1/PLLInst_0 
    (
        .CLKI(clk_25M_c),
        .CLKFB(\PLL_25to200_1/CLKINTFB_t ),
        .PHASESEL1(n_GND_c),
        .PHASESEL0(n_GND_c),
        .PHASEDIR(n_GND_c),
        .PHASESTEP(n_GND_c),
        .LOADREG(n_GND_c),
        .STDBY(n_GND_c),
        .PLLWAKESYNC(n_GND_c),
        .RST(n_GND_c),
        .RESETM(n_GND_c),
        .RESETC(n_GND_c),
        .RESETD(n_GND_c),
        .ENCLKOP(n_GND_c),
        .ENCLKOS(n_GND_c),
        .ENCLKOS2(n_GND_c),
        .ENCLKOS3(n_GND_c),
        .PLLCLK(n_GND_c),
        .PLLRST(n_GND_c),
        .PLLSTB(n_GND_c),
        .PLLWE(n_GND_c),
        .PLLDATI7(n_GND_c),
        .PLLDATI6(n_GND_c),
        .PLLDATI5(n_GND_c),
        .PLLDATI4(n_GND_c),
        .PLLDATI3(n_GND_c),
        .PLLDATI2(n_GND_c),
        .PLLDATI1(n_GND_c),
        .PLLDATI0(n_GND_c),
        .PLLADDR4(n_GND_c),
        .PLLADDR3(n_GND_c),
        .PLLADDR2(n_GND_c),
        .PLLADDR1(n_GND_c),
        .PLLADDR0(n_GND_c),
        .CLKOP(clk_200M),
        .CLKINTFB(\PLL_25to200_1/CLKINTFB_t )
    )
    /* synthesis FREQUENCY_PIN_CLKOP = "200.000000" */
    /* synthesis FREQUENCY_PIN_CLKI = "25.000000" */
    /* synthesis LPF_RESISTOR = "48" */
    /* synthesis FREQ_LOCK_ACCURACY = "2" */
    /* synthesis ICP_CURRENT = "8" */;

    defparam \PLL_25to200_1/PLLInst_0 .CLKFB_DIV = 8;
    defparam \PLL_25to200_1/PLLInst_0 .CLKI_DIV = 1;
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_CPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_DIV = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_SEL = "CLKO5";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOPD_DLY = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_CPHASE = 3;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_DIV = 4;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_ENABLE = "ENABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_TRIM_DELAY = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_TRIM_POL = "RISING";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS2_CPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS2_DIV = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS2_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS2_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS3_CPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS3_DIV = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS3_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS3_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_CPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_DIV = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_TRIM_DELAY = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_TRIM_POL = "RISING";
    defparam \PLL_25to200_1/PLLInst_0 .DCRST_ENA = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .DDRST_ENA = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .DPHASE_SOURCE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .EN_PHI = "FALSE";
    defparam \PLL_25to200_1/PLLInst_0 .FEEDBK_PATH = "INT_DIVA";
    defparam \PLL_25to200_1/PLLInst_0 .FRACN_DIV = 0;
    defparam \PLL_25to200_1/PLLInst_0 .FRACN_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .INTFB_WAKE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .MRST_ENA = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXA2 = "DIVA";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXB2 = "DIVB";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXC2 = "DIVC";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXD2 = "DIVD";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXE2 = "DIVE";
    defparam \PLL_25to200_1/PLLInst_0 .PLLRST_ENA = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .PLL_LOCK_MODE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .PLL_USE_WB = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .PREDIVIDER_MUXA1 = 0;
    defparam \PLL_25to200_1/PLLInst_0 .PREDIVIDER_MUXB1 = 0;
    defparam \PLL_25to200_1/PLLInst_0 .PREDIVIDER_MUXC1 = 0;
    defparam \PLL_25to200_1/PLLInst_0 .PREDIVIDER_MUXD1 = 0;
    defparam \PLL_25to200_1/PLLInst_0 .STDBY_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_A0 = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_B0 = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_C0 = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_D0 = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_E0 = "DISABLED";

    xsXORCY \led_wf1/_i_6/bitAdd_1/xorcy 
    (
        .CI(\led_wf1/cnt [0]),
        .LI(\led_wf1/cnt [1]),
        .O(\led_wf1/n_35[1] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_1/muxcy 
    (
        .CI(\led_wf1/cnt [0]),
        .DI(\led_wf1/cnt [1]),
        .S(\led_wf1/cnt [1]),
        .O(\led_wf1/_i_6/_n_1 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_2/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_1 ),
        .LI(\led_wf1/cnt [2]),
        .O(\led_wf1/n_35[2] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_2/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_1 ),
        .DI(\led_wf1/cnt [2]),
        .S(\led_wf1/cnt [2]),
        .O(\led_wf1/_i_6/_n_3 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_3/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_3 ),
        .LI(\led_wf1/cnt [3]),
        .O(\led_wf1/n_35[3] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_3/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_3 ),
        .DI(\led_wf1/cnt [3]),
        .S(\led_wf1/cnt [3]),
        .O(\led_wf1/_i_6/_n_5 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_4/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_5 ),
        .LI(\led_wf1/cnt [4]),
        .O(\led_wf1/n_35[4] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_4/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_5 ),
        .DI(\led_wf1/cnt [4]),
        .S(\led_wf1/cnt [4]),
        .O(\led_wf1/_i_6/_n_7 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_5/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_7 ),
        .LI(\led_wf1/cnt [5]),
        .O(\led_wf1/n_35[5] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_5/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_7 ),
        .DI(\led_wf1/cnt [5]),
        .S(\led_wf1/cnt [5]),
        .O(\led_wf1/_i_6/_n_9 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_6/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_9 ),
        .LI(\led_wf1/cnt [6]),
        .O(\led_wf1/n_35[6] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_6/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_9 ),
        .DI(\led_wf1/cnt [6]),
        .S(\led_wf1/cnt [6]),
        .O(\led_wf1/_i_6/_n_11 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_7/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_11 ),
        .LI(\led_wf1/cnt [7]),
        .O(\led_wf1/n_35[7] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_7/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_11 ),
        .DI(\led_wf1/cnt [7]),
        .S(\led_wf1/cnt [7]),
        .O(\led_wf1/_i_6/_n_13 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_8/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_13 ),
        .LI(\led_wf1/cnt [8]),
        .O(\led_wf1/n_35[8] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_8/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_13 ),
        .DI(\led_wf1/cnt [8]),
        .S(\led_wf1/cnt [8]),
        .O(\led_wf1/_i_6/_n_15 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_9/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_15 ),
        .LI(\led_wf1/cnt [9]),
        .O(\led_wf1/n_35[9] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_9/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_15 ),
        .DI(\led_wf1/cnt [9]),
        .S(\led_wf1/cnt [9]),
        .O(\led_wf1/_i_6/_n_17 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_10/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_17 ),
        .LI(\led_wf1/cnt [10]),
        .O(\led_wf1/n_35[10] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_10/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_17 ),
        .DI(\led_wf1/cnt [10]),
        .S(\led_wf1/cnt [10]),
        .O(\led_wf1/_i_6/_n_19 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_11/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_19 ),
        .LI(\led_wf1/cnt [11]),
        .O(\led_wf1/n_35[11] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_11/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_19 ),
        .DI(\led_wf1/cnt [11]),
        .S(\led_wf1/cnt [11]),
        .O(\led_wf1/_i_6/_n_21 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_12/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_21 ),
        .LI(\led_wf1/cnt [12]),
        .O(\led_wf1/n_35[12] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_12/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_21 ),
        .DI(\led_wf1/cnt [12]),
        .S(\led_wf1/cnt [12]),
        .O(\led_wf1/_i_6/_n_23 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_13/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_23 ),
        .LI(\led_wf1/cnt [13]),
        .O(\led_wf1/n_35[13] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_13/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_23 ),
        .DI(\led_wf1/cnt [13]),
        .S(\led_wf1/cnt [13]),
        .O(\led_wf1/_i_6/_n_25 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_14/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_25 ),
        .LI(\led_wf1/cnt [14]),
        .O(\led_wf1/n_35[14] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_14/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_25 ),
        .DI(\led_wf1/cnt [14]),
        .S(\led_wf1/cnt [14]),
        .O(\led_wf1/_i_6/_n_27 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_15/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_27 ),
        .LI(\led_wf1/cnt [15]),
        .O(\led_wf1/n_35[15] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_15/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_27 ),
        .DI(\led_wf1/cnt [15]),
        .S(\led_wf1/cnt [15]),
        .O(\led_wf1/_i_6/_n_29 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_16/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_29 ),
        .LI(\led_wf1/cnt [16]),
        .O(\led_wf1/n_35[16] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_16/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_29 ),
        .DI(\led_wf1/cnt [16]),
        .S(\led_wf1/cnt [16]),
        .O(\led_wf1/_i_6/_n_31 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_17/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_31 ),
        .LI(\led_wf1/cnt [17]),
        .O(\led_wf1/n_35[17] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_17/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_31 ),
        .DI(\led_wf1/cnt [17]),
        .S(\led_wf1/cnt [17]),
        .O(\led_wf1/_i_6/_n_33 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_18/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_33 ),
        .LI(\led_wf1/cnt [18]),
        .O(\led_wf1/n_35[18] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_18/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_33 ),
        .DI(\led_wf1/cnt [18]),
        .S(\led_wf1/cnt [18]),
        .O(\led_wf1/_i_6/_n_35 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_19/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_35 ),
        .LI(\led_wf1/cnt [19]),
        .O(\led_wf1/n_35[19] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_19/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_35 ),
        .DI(\led_wf1/cnt [19]),
        .S(\led_wf1/cnt [19]),
        .O(\led_wf1/_i_6/_n_37 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_20/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_37 ),
        .LI(\led_wf1/cnt [20]),
        .O(\led_wf1/n_35[20] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_20/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_37 ),
        .DI(\led_wf1/cnt [20]),
        .S(\led_wf1/cnt [20]),
        .O(\led_wf1/_i_6/_n_39 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_21/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_39 ),
        .LI(\led_wf1/cnt [21]),
        .O(\led_wf1/n_35[21] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_21/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_39 ),
        .DI(\led_wf1/cnt [21]),
        .S(\led_wf1/cnt [21]),
        .O(\led_wf1/_i_6/_n_41 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_22/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_41 ),
        .LI(\led_wf1/cnt [22]),
        .O(\led_wf1/n_35[22] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_22/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_41 ),
        .DI(\led_wf1/cnt [22]),
        .S(\led_wf1/cnt [22]),
        .O(\led_wf1/_i_6/_n_43 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_23/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_43 ),
        .LI(\led_wf1/cnt [23]),
        .O(\led_wf1/n_35[23] )
    );
    xsIOBI clk_25M_pad
    (
        .I(clk_25M),
        .O(clk_25M_c)
    );
    xsIOBI swdclk_pad
    (
        .I(swdclk),
        .O(swdclk_c)
    );
    xsIOBI \key_pin[1]_pad 
    (
        .I(key_pin[1]),
        .O(\key_pin[1]_c )
    );
    xsIOBI \key_pin[0]_pad 
    (
        .I(key_pin[0]),
        .O(\key_pin[0]_c )
    );
    xsIOBI uart_DAP_rx_pad
    (
        .I(uart_DAP_rx),
        .O(uart_DAP_rx_c)
    );
    xsIOBO led_core_pad
    (
        .I(led_core_c),
        .O(led_core)
    );
    xsIOBO \SRAM_ADDR[18]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[18])
    );
    xsIOBO \SRAM_ADDR[17]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[17])
    );
    xsIOBO \SRAM_ADDR[16]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[16])
    );
    xsIOBO \SRAM_ADDR[15]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[15])
    );
    xsIOBO \SRAM_ADDR[14]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[14])
    );
    xsIOBO \SRAM_ADDR[13]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[13])
    );
    xsIOBO \SRAM_ADDR[12]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[12])
    );
    xsIOBO \SRAM_ADDR[11]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[11])
    );
    xsIOBO \SRAM_ADDR[10]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[10])
    );
    xsIOBO \SRAM_ADDR[9]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[9])
    );
    xsIOBO \SRAM_ADDR[8]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[8])
    );
    xsIOBO \SRAM_ADDR[7]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[7])
    );
    xsIOBO \SRAM_ADDR[6]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[6])
    );
    xsIOBO \SRAM_ADDR[5]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[5])
    );
    xsIOBO \SRAM_ADDR[4]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[4])
    );
    xsIOBO \SRAM_ADDR[3]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[3])
    );
    xsIOBO \SRAM_ADDR[2]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[2])
    );
    xsIOBO \SRAM_ADDR[1]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[1])
    );
    xsIOBO \SRAM_ADDR[0]_pad 
    (
        .I(n_GND_c),
        .O(SRAM_ADDR[0])
    );
    xsIOBO SRAM_nWE_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nWE)
    );
    xsIOBO SRAM_nOE_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nOE)
    );
    xsIOBO SRAM_nCE_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nCE)
    );
    xsIOBO SRAM_nLB_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nLB)
    );
    xsIOBO SRAM_nUB_pad
    (
        .I(n_VCC_c),
        .O(SRAM_nUB)
    );
    xsIOBO flash_sclk_pad
    (
        .I(n_GND_c),
        .O(flash_sclk)
    );
    xsIOBO flash_cs_pad
    (
        .I(n_VCC_c),
        .O(flash_cs)
    );
    xsIOBO flash_mosi_pad
    (
        .I(n_GND_c),
        .O(flash_mosi)
    );
    xsIOBO \led_pin[3]_pad 
    (
        .I(\led_pin[3]_c ),
        .O(led_pin[3])
    );
    xsIOBO \led_pin[2]_pad 
    (
        .I(\led_pin[2]_c ),
        .O(led_pin[2])
    );
    xsIOBO \led_pin[1]_pad 
    (
        .I(\led_pin[1]_c ),
        .O(led_pin[1])
    );
    xsIOBO \led_pin[0]_pad 
    (
        .I(osc_c6_pin_c),
        .O(led_pin[0])
    );
    xsIOBO beep_pin_pad
    (
        .I(beep_pin_c),
        .O(beep_pin)
    );
    xsIOBO uart_DAP_tx_pad
    (
        .I(uart_DAP_tx_c),
        .O(uart_DAP_tx)
    );
    xsIOBO uart_ch340_tx_pad
    (
        .I(n_GND_c),
        .O(uart_ch340_tx)
    );
    xsIOBO sd_sclk_pad
    (
        .I(n_GND_c),
        .O(sd_sclk)
    );
    xsIOBO sd_cs_pad
    (
        .I(n_VCC_c),
        .O(sd_cs)
    );
    xsIOBO sd_mosi_pad
    (
        .I(n_GND_c),
        .O(sd_mosi)
    );
    xsIOBO w5500_sclk_pad
    (
        .I(n_GND_c),
        .O(w5500_sclk)
    );
    xsIOBO w5500_cs_pad
    (
        .I(n_VCC_c),
        .O(w5500_cs)
    );
    xsIOBO w5500_mosi_pad
    (
        .I(n_GND_c),
        .O(w5500_mosi)
    );
    xsIOBO seg7_SH_CP_pad
    (
        .I(n_GND_c),
        .O(seg7_SH_CP)
    );
    xsIOBO seg7_ST_CP_pad
    (
        .I(n_VCC_c),
        .O(seg7_ST_CP)
    );
    xsIOBO seg7_DS_pad
    (
        .I(n_GND_c),
        .O(seg7_DS)
    );
    xsIOBO osc_c6_pin_pad
    (
        .I(osc_c6_pin_c),
        .O(osc_c6_pin)
    );
    xsIOBB swddio_pad
    (
        .I(\cm3inst/TMSO ),
        .T(\cm3inst/TMSOEN ),
        .O(_n_142_combout),
        .B(swddio)
    );
    xsDFFSA_K1C1E1 \led_wf1/led_sig_reg[0] 
    (
        .C(clk_25M_c),
        .CE(_n_140),
        .CLR(\led_wf1/n_3 ),
        .D(\led_pin[1]_c ),
        .Q(osc_c6_pin_c)
    );
    defparam \led_wf1/led_sig_reg[0] .INIT = 1'B0;

    xsDFFSA_K1P1E1 \led_wf1/led_sig_reg[1] 
    (
        .C(clk_25M_c),
        .CE(_n_140),
        .D(\led_pin[2]_c ),
        .PRE(\led_wf1/n_3 ),
        .Q(\led_pin[1]_c )
    );
    defparam \led_wf1/led_sig_reg[1] .INIT = 1'B1;

    xsDFFSA_K1P1E1 \led_wf1/led_sig_reg[2] 
    (
        .C(clk_25M_c),
        .CE(_n_140),
        .D(\led_pin[3]_c ),
        .PRE(\led_wf1/n_3 ),
        .Q(\led_pin[2]_c )
    );
    defparam \led_wf1/led_sig_reg[2] .INIT = 1'B1;

    xsDFFSA_K1P1E1 \led_wf1/led_sig_reg[3] 
    (
        .C(clk_25M_c),
        .CE(_n_140),
        .D(osc_c6_pin_c),
        .PRE(\led_wf1/n_3 ),
        .Q(\led_pin[3]_c )
    );
    defparam \led_wf1/led_sig_reg[3] .INIT = 1'B1;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[23] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_34 ),
        .Q(\led_wf1/cnt [23])
    );
    defparam \led_wf1/cnt_reg[23] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[22] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_33 ),
        .Q(\led_wf1/cnt [22])
    );
    defparam \led_wf1/cnt_reg[22] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[21] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_32 ),
        .Q(\led_wf1/cnt [21])
    );
    defparam \led_wf1/cnt_reg[21] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[20] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_31 ),
        .Q(\led_wf1/cnt [20])
    );
    defparam \led_wf1/cnt_reg[20] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[19] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_30 ),
        .Q(\led_wf1/cnt [19])
    );
    defparam \led_wf1/cnt_reg[19] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[18] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_29 ),
        .Q(\led_wf1/cnt [18])
    );
    defparam \led_wf1/cnt_reg[18] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[17] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_28 ),
        .Q(\led_wf1/cnt [17])
    );
    defparam \led_wf1/cnt_reg[17] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[16] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_27 ),
        .Q(\led_wf1/cnt [16])
    );
    defparam \led_wf1/cnt_reg[16] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[15] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_26 ),
        .Q(\led_wf1/cnt [15])
    );
    defparam \led_wf1/cnt_reg[15] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[14] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_25 ),
        .Q(\led_wf1/cnt [14])
    );
    defparam \led_wf1/cnt_reg[14] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[13] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_24 ),
        .Q(\led_wf1/cnt [13])
    );
    defparam \led_wf1/cnt_reg[13] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[12] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_23 ),
        .Q(\led_wf1/cnt [12])
    );
    defparam \led_wf1/cnt_reg[12] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[11] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_22 ),
        .Q(\led_wf1/cnt [11])
    );
    defparam \led_wf1/cnt_reg[11] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[10] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_21 ),
        .Q(\led_wf1/cnt [10])
    );
    defparam \led_wf1/cnt_reg[10] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[9] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_20 ),
        .Q(\led_wf1/cnt [9])
    );
    defparam \led_wf1/cnt_reg[9] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[8] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_19 ),
        .Q(\led_wf1/cnt [8])
    );
    defparam \led_wf1/cnt_reg[8] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[7] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_18 ),
        .Q(\led_wf1/cnt [7])
    );
    defparam \led_wf1/cnt_reg[7] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[6] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_17 ),
        .Q(\led_wf1/cnt [6])
    );
    defparam \led_wf1/cnt_reg[6] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[5] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_16 ),
        .Q(\led_wf1/cnt [5])
    );
    defparam \led_wf1/cnt_reg[5] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[4] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_15 ),
        .Q(\led_wf1/cnt [4])
    );
    defparam \led_wf1/cnt_reg[4] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[3] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_14 ),
        .Q(\led_wf1/cnt [3])
    );
    defparam \led_wf1/cnt_reg[3] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[2] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_13 ),
        .Q(\led_wf1/cnt [2])
    );
    defparam \led_wf1/cnt_reg[2] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[1] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_12 ),
        .Q(\led_wf1/cnt [1])
    );
    defparam \led_wf1/cnt_reg[1] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[0] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_11 ),
        .Q(\led_wf1/cnt [0])
    );
    defparam \led_wf1/cnt_reg[0] .INIT = 1'B0;

    xsLUTSA2 \led_wf1/_i_8 
    (
        .I0(\led_wf1/cnt [0]),
        .I1(_n_140),
        .O(\led_wf1/n_11 )
    );
    defparam \led_wf1/_i_8 .INIT = 4'H1;

    xsLUTSA2 \led_wf1/_i_9 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[1] ),
        .O(\led_wf1/n_12 )
    );
    defparam \led_wf1/_i_9 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_10 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[2] ),
        .O(\led_wf1/n_13 )
    );
    defparam \led_wf1/_i_10 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_11 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[3] ),
        .O(\led_wf1/n_14 )
    );
    defparam \led_wf1/_i_11 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_12 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[4] ),
        .O(\led_wf1/n_15 )
    );
    defparam \led_wf1/_i_12 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_13 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[5] ),
        .O(\led_wf1/n_16 )
    );
    defparam \led_wf1/_i_13 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_14 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[6] ),
        .O(\led_wf1/n_17 )
    );
    defparam \led_wf1/_i_14 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_15 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[7] ),
        .O(\led_wf1/n_18 )
    );
    defparam \led_wf1/_i_15 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_16 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[8] ),
        .O(\led_wf1/n_19 )
    );
    defparam \led_wf1/_i_16 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_17 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[9] ),
        .O(\led_wf1/n_20 )
    );
    defparam \led_wf1/_i_17 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_18 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[10] ),
        .O(\led_wf1/n_21 )
    );
    defparam \led_wf1/_i_18 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_19 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[11] ),
        .O(\led_wf1/n_22 )
    );
    defparam \led_wf1/_i_19 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_20 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[12] ),
        .O(\led_wf1/n_23 )
    );
    defparam \led_wf1/_i_20 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_21 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[13] ),
        .O(\led_wf1/n_24 )
    );
    defparam \led_wf1/_i_21 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_22 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[14] ),
        .O(\led_wf1/n_25 )
    );
    defparam \led_wf1/_i_22 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_23 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[15] ),
        .O(\led_wf1/n_26 )
    );
    defparam \led_wf1/_i_23 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_24 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[16] ),
        .O(\led_wf1/n_27 )
    );
    defparam \led_wf1/_i_24 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_25 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[17] ),
        .O(\led_wf1/n_28 )
    );
    defparam \led_wf1/_i_25 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_26 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[18] ),
        .O(\led_wf1/n_29 )
    );
    defparam \led_wf1/_i_26 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_27 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[19] ),
        .O(\led_wf1/n_30 )
    );
    defparam \led_wf1/_i_27 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_28 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[20] ),
        .O(\led_wf1/n_31 )
    );
    defparam \led_wf1/_i_28 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_29 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[21] ),
        .O(\led_wf1/n_32 )
    );
    defparam \led_wf1/_i_29 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_30 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[22] ),
        .O(\led_wf1/n_33 )
    );
    defparam \led_wf1/_i_30 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_31 
    (
        .I0(_n_140),
        .I1(\led_wf1/n_35[23] ),
        .O(\led_wf1/n_34 )
    );
    defparam \led_wf1/_i_31 .INIT = 4'H4;

    xsLUTSA6 \inverted_led_wf1/_i_2/_i_0 
    (
        .I0(\led_wf1/cnt [23]),
        .I1(\led_wf1/cnt [22]),
        .I2(\led_wf1/cnt [21]),
        .I3(\led_wf1/cnt [20]),
        .I4(_n_141),
        .I5(\led_wf1/_i_2/_i_0_rkd_16 ),
        .O(_n_140)
    );
    defparam \inverted_led_wf1/_i_2/_i_0 .INIT = 64'H0000001000000000;

    xsLUTSA4 \led_wf1/_i_2/_i_0_rkd_16:0 
    (
        .I0(\led_wf1/cnt [19]),
        .I1(\led_wf1/cnt [18]),
        .I2(\led_wf1/cnt [17]),
        .I3(\led_wf1/cnt [16]),
        .O(\led_wf1/_i_2/_i_0_rkd_16 )
    );
    defparam \led_wf1/_i_2/_i_0_rkd_16:0 .INIT = 16'H0040;

    xsLUTSA6 \dec_of_inverted_led_wf1/_i_2/_i_0 
    (
        .I0(\led_wf1/cnt [7]),
        .I1(\led_wf1/cnt [6]),
        .I2(\led_wf1/cnt [5]),
        .I3(\led_wf1/cnt [4]),
        .I4(\led_wf1/_i_2/_i_0_rkd_12 ),
        .I5(\led_wf1/_i_2/_i_0_rkd_19 ),
        .O(_n_141)
    );
    defparam \dec_of_inverted_led_wf1/_i_2/_i_0 .INIT = 64'HFFFFFFFFFDFFFFFF;

    xsLUTSA5 \led_wf1/_i_2/_i_0_rkd_19:0 
    (
        .I0(\led_wf1/cnt [15]),
        .I1(\led_wf1/cnt [14]),
        .I2(\led_wf1/cnt [13]),
        .I3(\led_wf1/cnt [12]),
        .I4(\led_wf1/_i_2/_i_0_rkd_14 ),
        .O(\led_wf1/_i_2/_i_0_rkd_19 )
    );
    defparam \led_wf1/_i_2/_i_0_rkd_19:0 .INIT = 32'HFFEFFFFF;

    xsLUTSA4 \led_wf1/_i_2/_i_0_rkd_14:0 
    (
        .I0(\led_wf1/cnt [11]),
        .I1(\led_wf1/cnt [10]),
        .I2(\led_wf1/cnt [9]),
        .I3(\led_wf1/cnt [8]),
        .O(\led_wf1/_i_2/_i_0_rkd_14 )
    );
    defparam \led_wf1/_i_2/_i_0_rkd_14:0 .INIT = 16'H0400;

    xsLUTSA4 \led_wf1/_i_2/_i_0_rkd_12:0 
    (
        .I0(\led_wf1/cnt [3]),
        .I1(\led_wf1/cnt [2]),
        .I2(\led_wf1/cnt [1]),
        .I3(\led_wf1/cnt [0]),
        .O(\led_wf1/_i_2/_i_0_rkd_12 )
    );
    defparam \led_wf1/_i_2/_i_0_rkd_12:0 .INIT = 16'H8000;

    xsINVSA \led_wf1/_i_0 
    (
        .I(\key_pin[1]_c ),
        .O(\led_wf1/n_3 )
    );
    xs0 _i_5
    (
        .G(n_GND_c)
    );
    xs1 _i_4
    (
        .P(n_VCC_c)
    );


endmodule
