
//=========oOOOo===========================================oOOOo==========
//  Verilog file generated by HqFpga(TM) v2.14.4 (Winter 2023) Build 021824
//  Time : Sun Feb 25 16:20:33 2024

//  Xian Intelligence Silicon Technology, Inc.(XiST)
//========================================================================
	

// work.top(top)
module top
(
    clk_27M,
    clk_25M,
    clk_p3,
    clk_p4,
    clk_p5,
    flash_miso,
    swdclk,
    key_pin,
    uart_DAP_rx,
    uart_ch340_rx,
    sd_miso,
    w5500_rstn,
    w5500_intn,
    w5500_miso,
    led_core,
    pll_i2c_scl,
    SRAM_ADDR,
    SRAM_nWE,
    SRAM_nOE,
    SRAM_nCE,
    SRAM_nLB,
    SRAM_nUB,
    flash_sclk,
    flash_cs,
    flash_mosi,
    led_pin,
    beep_pin,
    uart_DAP_tx,
    uart_ch340_tx,
    sd_sclk,
    sd_cs,
    sd_mosi,
    w5500_sclk,
    w5500_cs,
    w5500_mosi,
    seg7_SH_CP,
    seg7_ST_CP,
    seg7_DS,
    i2c_scl,
    osc_c6_pin,
    pll_i2c_sda,
    SRAM_DQ,
    swddio,
    i2c_sda
);
    input  clk_27M;
    input  clk_25M;
    input  clk_p3;
    input  clk_p4;
    input  clk_p5;
    input  flash_miso;
    input  swdclk;
    input  [2:0] key_pin;
    input  uart_DAP_rx;
    input  uart_ch340_rx;
    input  sd_miso;
    input  w5500_rstn;
    input  w5500_intn;
    input  w5500_miso;
    output led_core;
    output pll_i2c_scl;
    output [18:0] SRAM_ADDR;
    output SRAM_nWE;
    output SRAM_nOE;
    output SRAM_nCE;
    output SRAM_nLB;
    output SRAM_nUB;
    output flash_sclk;
    output flash_cs;
    output flash_mosi;
    output [3:0] led_pin;
    output beep_pin;
    output uart_DAP_tx;
    output uart_ch340_tx;
    output sd_sclk;
    output sd_cs;
    output sd_mosi;
    output w5500_sclk;
    output w5500_cs;
    output w5500_mosi;
    output seg7_SH_CP;
    output seg7_ST_CP;
    output seg7_DS;
    output i2c_scl;
    output osc_c6_pin;
    inout  pll_i2c_sda;
    inout  [15:0] SRAM_DQ;
    inout  swddio;
    inout  i2c_sda;
    wire clk_100M;
    wire \led_wf1/n_3 ;
    wire [23:0] \led_wf1/cnt ;
    wire \led_wf1/n_11 ;
    wire \led_wf1/n_12 ;
    wire \led_wf1/n_13 ;
    wire \led_wf1/n_14 ;
    wire \led_wf1/n_15 ;
    wire \led_wf1/n_16 ;
    wire \led_wf1/n_17 ;
    wire \led_wf1/n_18 ;
    wire \led_wf1/n_19 ;
    wire \led_wf1/n_20 ;
    wire \led_wf1/n_21 ;
    wire \led_wf1/n_22 ;
    wire \led_wf1/n_23 ;
    wire \led_wf1/n_24 ;
    wire \led_wf1/n_25 ;
    wire \led_wf1/n_26 ;
    wire \led_wf1/n_27 ;
    wire \led_wf1/n_28 ;
    wire \led_wf1/n_29 ;
    wire \led_wf1/n_30 ;
    wire \led_wf1/n_31 ;
    wire \led_wf1/n_32 ;
    wire \led_wf1/n_33 ;
    wire \led_wf1/n_34 ;
    wire \cm3inst/TMSO ;
    wire \cm3inst/TMSOEN ;
    wire [31:0] \cm3inst/TARGEXP0HADDR ;
    wire \cm3inst/TARGEXP0HREADYMUX ;
    wire \cm3inst/TARGEXP0HREADYOUT ;
    wire \cm3inst/TARGEXP0HSEL ;
    wire [2:0] \cm3inst/TARGEXP0HSIZE ;
    wire [1:0] \cm3inst/TARGEXP0HTRANS ;
    wire [31:0] \cm3inst/TARGEXP0HWDATA ;
    wire \cm3inst/TARGEXP0HWRITE ;
    wire \PLL_25to200_1/CLKINTFB_t ;
    wire \led_wf1/n_35[1] ;
    wire \led_wf1/_i_6/_n_1 ;
    wire \led_wf1/n_35[2] ;
    wire \led_wf1/_i_6/_n_3 ;
    wire \led_wf1/n_35[3] ;
    wire \led_wf1/_i_6/_n_5 ;
    wire \led_wf1/n_35[4] ;
    wire \led_wf1/_i_6/_n_7 ;
    wire \led_wf1/n_35[5] ;
    wire \led_wf1/_i_6/_n_9 ;
    wire \led_wf1/n_35[6] ;
    wire \led_wf1/_i_6/_n_11 ;
    wire \led_wf1/n_35[7] ;
    wire \led_wf1/_i_6/_n_13 ;
    wire \led_wf1/n_35[8] ;
    wire \led_wf1/_i_6/_n_15 ;
    wire \led_wf1/n_35[9] ;
    wire \led_wf1/_i_6/_n_17 ;
    wire \led_wf1/n_35[10] ;
    wire \led_wf1/_i_6/_n_19 ;
    wire \led_wf1/n_35[11] ;
    wire \led_wf1/_i_6/_n_21 ;
    wire \led_wf1/n_35[12] ;
    wire \led_wf1/_i_6/_n_23 ;
    wire \led_wf1/n_35[13] ;
    wire \led_wf1/_i_6/_n_25 ;
    wire \led_wf1/n_35[14] ;
    wire \led_wf1/_i_6/_n_27 ;
    wire \led_wf1/n_35[15] ;
    wire \led_wf1/_i_6/_n_29 ;
    wire \led_wf1/n_35[16] ;
    wire \led_wf1/_i_6/_n_31 ;
    wire \led_wf1/n_35[17] ;
    wire \led_wf1/_i_6/_n_33 ;
    wire \led_wf1/n_35[18] ;
    wire \led_wf1/_i_6/_n_35 ;
    wire \led_wf1/n_35[19] ;
    wire \led_wf1/_i_6/_n_37 ;
    wire \led_wf1/n_35[20] ;
    wire \led_wf1/_i_6/_n_39 ;
    wire \led_wf1/n_35[21] ;
    wire \led_wf1/_i_6/_n_41 ;
    wire \led_wf1/n_35[22] ;
    wire \led_wf1/_i_6/_n_43 ;
    wire \led_wf1/n_35[23] ;
    wire \cm3inst/ahb_sram1/trans_valid ;
    wire \cm3inst/ahb_sram1/n_53 ;
    wire \cm3inst/ahb_sram1/DONE ;
    wire \cm3inst/ahb_sram1/reg_rd_req ;
    wire \cm3inst/ahb_sram1/reg_wr_req ;
    wire \cm3inst/ahb_sram1/reg_write ;
    wire \cm3inst/ahb_sram1/reg_active ;
    wire [1:0] \cm3inst/ahb_sram1/reg_lb_mux ;
    wire [1:0] \cm3inst/ahb_sram1/reg_size ;
    wire [2:0] \cm3inst/ahb_sram1/reg_mcount ;
    wire \cm3inst/ahb_sram1/last_operation ;
    wire \cm3inst/ahb_sram1/n_100 ;
    wire \cm3inst/ahb_sram1/n_119 ;
    wire [1:0] \cm3inst/ahb_sram1/reg_byte_mask ;
    wire \cm3inst/ahb_sram1/n_120 ;
    wire \cm3inst/ahb_sram1/n_122 ;
    wire [1:0] \cm3inst/ahb_sram1/reg_ub_mux ;
    wire [15:0] \cm3inst/ahb_sram1/DATAOUT ;
    wire \cm3inst/ahb_sram1/n_132 ;
    wire [7:0] \cm3inst/ahb_sram1/read_buffer_0 ;
    wire \cm3inst/ahb_sram1/n_135 ;
    wire [7:0] \cm3inst/ahb_sram1/read_buffer_1 ;
    wire [1:0] \cm3inst/ahb_sram1/nxt_bs_n ;
    wire \cm3inst/ahb_sram1/nxt_ce_n ;
    wire \cm3inst/ahb_sram1/nxt_dataoe_n ;
    wire \cm3inst/ahb_sram1/DATAOEn ;
    wire \cm3inst/ahb_sram1/n_154 ;
    wire \cm3inst/ahb_sram1/n_155 ;
    wire \cm3inst/ahb_sram1/n_156 ;
    wire \cm3inst/ahb_sram1/nxt_oe_n ;
    wire \cm3inst/ahb_sram1/nxt_we_n ;
    wire \cm3inst/ahb_sram1/n_162 ;
    wire \cm3inst/ahb_sram1/n_195 ;
    wire \cm3inst/ahb_sram1/n_198 ;
    wire \cm3inst/ahb_sram1/n_201 ;
    wire \cm3inst/ahb_sram1/n_206 ;
    wire \cm3inst/ahb_sram1/n_208 ;
    wire \cm3inst/ahb_sram1/n_211 ;
    wire \cm3inst/ahb_sram1/n_218 ;
    wire \cm3inst/ahb_sram1/n_97 ;
    wire \cm3inst/ahb_sram1/i_dataout[0] ;
    wire \cm3inst/ahb_sram1/i_dataout[1] ;
    wire \cm3inst/ahb_sram1/i_dataout[2] ;
    wire \cm3inst/ahb_sram1/i_dataout[3] ;
    wire \cm3inst/ahb_sram1/i_dataout[4] ;
    wire \cm3inst/ahb_sram1/i_dataout[5] ;
    wire \cm3inst/ahb_sram1/i_dataout[6] ;
    wire \cm3inst/ahb_sram1/i_dataout[7] ;
    wire \cm3inst/ahb_sram1/i_dataout[8] ;
    wire \cm3inst/ahb_sram1/i_dataout[9] ;
    wire \cm3inst/ahb_sram1/i_dataout[10] ;
    wire \cm3inst/ahb_sram1/i_dataout[11] ;
    wire \cm3inst/ahb_sram1/i_dataout[12] ;
    wire \cm3inst/ahb_sram1/i_dataout[13] ;
    wire \cm3inst/ahb_sram1/i_dataout[14] ;
    wire \cm3inst/ahb_sram1/i_dataout[15] ;
    wire \cm3inst/ahb_sram1/RDREQ ;
    wire \cm3inst/ahb_sram1/WRREQ ;
    wire \cm3inst/ahb_sram1/nxt_addr_low[1] ;
    wire \cm3inst/ahb_sram1/nxt_lb_mux[1] ;
    wire \cm3inst/ahb_sram1/nxt_ub_mux[1] ;
    wire \cm3inst/TARGEXP0HRDATA[0] ;
    wire \cm3inst/TARGEXP0HRDATA[1] ;
    wire \cm3inst/TARGEXP0HRDATA[2] ;
    wire \cm3inst/TARGEXP0HRDATA[3] ;
    wire \cm3inst/TARGEXP0HRDATA[4] ;
    wire \cm3inst/TARGEXP0HRDATA[5] ;
    wire \cm3inst/TARGEXP0HRDATA[6] ;
    wire \cm3inst/TARGEXP0HRDATA[7] ;
    wire \cm3inst/TARGEXP0HRDATA[8] ;
    wire \cm3inst/TARGEXP0HRDATA[9] ;
    wire \cm3inst/TARGEXP0HRDATA[10] ;
    wire \cm3inst/TARGEXP0HRDATA[11] ;
    wire \cm3inst/TARGEXP0HRDATA[12] ;
    wire \cm3inst/TARGEXP0HRDATA[13] ;
    wire \cm3inst/TARGEXP0HRDATA[14] ;
    wire \cm3inst/TARGEXP0HRDATA[15] ;
    wire \cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ;
    wire net_extracted_nHQX15;
    wire \cm3inst/ahb_sram1/_i_307_decomp ;
    wire net_extracted_nHQX1;
    wire net_extracted_nHQX4;
    wire \cm3inst/ahb_sram1/_i_182_decomp ;
    wire \led_wf1/_i_2/_i_0_rkd_12 ;
    wire \led_wf1/_i_2/_i_0_rkd_14 ;
    wire \led_wf1/_i_2/_i_0_rkd_16 ;
    wire \led_wf1/_i_2/_i_0_rkd_19 ;
    wire _n_1089;
    wire _n_1090;
    wire _n_1091;
    wire \cm3inst/ahb_sram1/last_operation_reg_ctrl_din ;
    wire clk_25M_c;
    wire swdclk_c;
    wire \key_pin[1]_c ;
    wire \key_pin[0]_c ;
    wire uart_DAP_rx_c;
    wire led_core_c;
    wire \SRAM_ADDR[18]_c ;
    wire \SRAM_ADDR[17]_c ;
    wire \SRAM_ADDR[16]_c ;
    wire \SRAM_ADDR[15]_c ;
    wire \SRAM_ADDR[14]_c ;
    wire \SRAM_ADDR[13]_c ;
    wire \SRAM_ADDR[12]_c ;
    wire \SRAM_ADDR[11]_c ;
    wire \SRAM_ADDR[10]_c ;
    wire \SRAM_ADDR[9]_c ;
    wire \SRAM_ADDR[8]_c ;
    wire \SRAM_ADDR[7]_c ;
    wire \SRAM_ADDR[6]_c ;
    wire \SRAM_ADDR[5]_c ;
    wire \SRAM_ADDR[4]_c ;
    wire \SRAM_ADDR[3]_c ;
    wire \SRAM_ADDR[2]_c ;
    wire \SRAM_ADDR[1]_c ;
    wire \SRAM_ADDR[0]_c ;
    wire SRAM_nWE_c;
    wire SRAM_nOE_c;
    wire SRAM_nCE_c;
    wire SRAM_nLB_c;
    wire SRAM_nUB_c;
    wire \led_pin[3]_c ;
    wire \led_pin[2]_c ;
    wire \led_pin[1]_c ;
    wire beep_pin_c;
    wire uart_DAP_tx_c;
    wire n_VCC_c;
    wire n_GND_c;
    wire osc_c6_pin_c;
    wire _n_1119_combout;
    wire _n_1120_combout;
    wire _n_1121_combout;
    wire _n_1122_combout;
    wire _n_1123_combout;
    wire _n_1124_combout;
    wire _n_1125_combout;
    wire _n_1126_combout;
    wire _n_1127_combout;
    wire _n_1128_combout;
    wire _n_1129_combout;
    wire _n_1130_combout;
    wire _n_1131_combout;
    wire _n_1132_combout;
    wire _n_1133_combout;
    wire _n_1134_combout;
    wire _n_1135_combout;

    xsCM3 \cm3inst/inst 
    (
        .DBG_SWDI_TMS(_n_1135_combout),
        .CS_TCK(swdclk_c),
        .CIBCLK(clk_100M),
        .CPURSTN(\key_pin[0]_c ),
        .INITEXP0HMASTLOCK(n_GND_c),
        .INITEXP0HSEL(n_GND_c),
        .INITEXP0HWRITE(n_GND_c),
        .INITEXP1HMASTLOCK(n_GND_c),
        .INITEXP1HSEL(n_GND_c),
        .INITEXP1HWRITE(n_GND_c),
        .MTXRSTN(\key_pin[0]_c ),
        .NSRST(n_VCC_c),
        .NTRST(n_VCC_c),
        .TARGEXP0HREADYOUT(\cm3inst/TARGEXP0HREADYOUT ),
        .TARGEXP0HRESP(n_GND_c),
        .TARGEXP1HREADYOUT(n_VCC_c),
        .TARGEXP1HRESP(n_GND_c),
        .TREECLK(clk_100M),
        .DBG_SWDO(\cm3inst/TMSO ),
        .DBG_SWDO_EN(\cm3inst/TMSOEN ),
        .TARGEXP0HREADYMUX(\cm3inst/TARGEXP0HREADYMUX ),
        .TARGEXP0HSEL(\cm3inst/TARGEXP0HSEL ),
        .TARGEXP0HWRITE(\cm3inst/TARGEXP0HWRITE ),
        .TARGEXP0HTRANS({\cm3inst/TARGEXP0HTRANS [1], HQSYN__DUMMY__0}),
        .INITEXP1HBURST({3{n_GND_c}}),
        .INITEXP1HSIZE({3{n_GND_c}}),
        .GPIOI({{29{n_GND_c}}, uart_DAP_rx_c, {2{n_GND_c}}}),
        .INITEXP0HSIZE({3{n_GND_c}}),
        .INITEXP0HBURST({3{n_GND_c}}),
        .GPIOO({HQSYN__DUMMY__1, HQSYN__DUMMY__2, HQSYN__DUMMY__3, HQSYN__DUMMY__4, HQSYN__DUMMY__5, HQSYN__DUMMY__6, HQSYN__DUMMY__7, HQSYN__DUMMY__8, HQSYN__DUMMY__9, HQSYN__DUMMY__10, HQSYN__DUMMY__11, HQSYN__DUMMY__12, HQSYN__DUMMY__13, HQSYN__DUMMY__14, HQSYN__DUMMY__15, HQSYN__DUMMY__16, HQSYN__DUMMY__17, HQSYN__DUMMY__18, HQSYN__DUMMY__19, HQSYN__DUMMY__20, HQSYN__DUMMY__21, HQSYN__DUMMY__22, HQSYN__DUMMY__23, HQSYN__DUMMY__24, HQSYN__DUMMY__25, HQSYN__DUMMY__26, HQSYN__DUMMY__27, HQSYN__DUMMY__28, uart_DAP_tx_c, HQSYN__DUMMY__29, beep_pin_c, led_core_c}),
        .DMACBREQ({4{n_GND_c}}),
        .TARGEXP0HSIZE({HQSYN__DUMMY__30, \cm3inst/TARGEXP0HSIZE [1:0]}),
        .INITEXP1HWDATA({32{n_GND_c}}),
        .DMACLBREQ({4{n_GND_c}}),
        .DMACSREQ({4{n_GND_c}}),
        .TARGEXP1HRDATA({32{n_GND_c}}),
        .DMACLSREQ({4{n_GND_c}}),
        .INITEXP1HADDR({32{n_GND_c}}),
        .INITEXP0HWDATA({32{n_GND_c}}),
        .INITEXP0HADDR({32{n_GND_c}}),
        .INITEXP1HPROT({4{n_GND_c}}),
        .EXTINT({16{n_GND_c}}),
        .TARGEXP0HWDATA(\cm3inst/TARGEXP0HWDATA ),
        .INITEXP0HPROT({4{n_GND_c}}),
        .TARGEXP0HRDATA({_n_1119_combout, _n_1120_combout, _n_1121_combout, _n_1122_combout, _n_1123_combout, _n_1124_combout, _n_1125_combout, _n_1126_combout, _n_1127_combout, _n_1128_combout, _n_1129_combout, _n_1130_combout, _n_1131_combout, _n_1132_combout, _n_1133_combout, _n_1134_combout, \cm3inst/TARGEXP0HRDATA[15] , \cm3inst/TARGEXP0HRDATA[14] , \cm3inst/TARGEXP0HRDATA[13] , \cm3inst/TARGEXP0HRDATA[12] , \cm3inst/TARGEXP0HRDATA[11] , \cm3inst/TARGEXP0HRDATA[10] , \cm3inst/TARGEXP0HRDATA[9] , \cm3inst/TARGEXP0HRDATA[8] , \cm3inst/TARGEXP0HRDATA[7] , \cm3inst/TARGEXP0HRDATA[6] , \cm3inst/TARGEXP0HRDATA[5] , \cm3inst/TARGEXP0HRDATA[4] , \cm3inst/TARGEXP0HRDATA[3] , \cm3inst/TARGEXP0HRDATA[2] , \cm3inst/TARGEXP0HRDATA[1] , \cm3inst/TARGEXP0HRDATA[0] }),
        .TARGEXP0HADDR({HQSYN__DUMMY__31, HQSYN__DUMMY__32, HQSYN__DUMMY__33, HQSYN__DUMMY__34, HQSYN__DUMMY__35, HQSYN__DUMMY__36, HQSYN__DUMMY__37, HQSYN__DUMMY__38, HQSYN__DUMMY__39, HQSYN__DUMMY__40, HQSYN__DUMMY__41, HQSYN__DUMMY__42, \cm3inst/TARGEXP0HADDR [19:0]}),
        .INITEXP1HTRANS({2{n_GND_c}}),
        .INITEXP0HTRANS({2{n_GND_c}})
    );
    defparam \cm3inst/inst .CORECLK = "CIB_CLK";
    defparam \cm3inst/inst .CORECLK_EN = "TRUE";
    defparam \cm3inst/inst .CORE_SET = "TRUE";
    defparam \cm3inst/inst .MTXCLK = "CORECLK";
    defparam \cm3inst/inst .PCLK_DIV = 0;
    defparam \cm3inst/inst .RSTN_ENABLE = "TRUE";

    xsPLLSA \PLL_25to200_1/PLLInst_0 
    (
        .CLKI(clk_25M_c),
        .CLKFB(\PLL_25to200_1/CLKINTFB_t ),
        .PHASESEL1(n_GND_c),
        .PHASESEL0(n_GND_c),
        .PHASEDIR(n_GND_c),
        .PHASESTEP(n_GND_c),
        .LOADREG(n_GND_c),
        .STDBY(n_GND_c),
        .PLLWAKESYNC(n_GND_c),
        .RST(n_GND_c),
        .RESETM(n_GND_c),
        .RESETC(n_GND_c),
        .RESETD(n_GND_c),
        .ENCLKOP(n_GND_c),
        .ENCLKOS(n_GND_c),
        .ENCLKOS2(n_GND_c),
        .ENCLKOS3(n_GND_c),
        .PLLCLK(n_GND_c),
        .PLLRST(n_GND_c),
        .PLLSTB(n_GND_c),
        .PLLWE(n_GND_c),
        .PLLDATI7(n_GND_c),
        .PLLDATI6(n_GND_c),
        .PLLDATI5(n_GND_c),
        .PLLDATI4(n_GND_c),
        .PLLDATI3(n_GND_c),
        .PLLDATI2(n_GND_c),
        .PLLDATI1(n_GND_c),
        .PLLDATI0(n_GND_c),
        .PLLADDR4(n_GND_c),
        .PLLADDR3(n_GND_c),
        .PLLADDR2(n_GND_c),
        .PLLADDR1(n_GND_c),
        .PLLADDR0(n_GND_c),
        .CLKOS(clk_100M),
        .CLKINTFB(\PLL_25to200_1/CLKINTFB_t )
    )
    /* synthesis FREQUENCY_PIN_CLKOS2 = "50.000000" */
    /* synthesis FREQUENCY_PIN_CLKOS = "100.000000" */
    /* synthesis FREQUENCY_PIN_CLKOP = "200.000000" */
    /* synthesis FREQUENCY_PIN_CLKI = "25.000000" */
    /* synthesis LPF_RESISTOR = "48" */
    /* synthesis FREQ_LOCK_ACCURACY = "2" */
    /* synthesis ICP_CURRENT = "8" */;

    defparam \PLL_25to200_1/PLLInst_0 .CLKFB_DIV = 8;
    defparam \PLL_25to200_1/PLLInst_0 .CLKI_DIV = 1;
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_CPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_DIV = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKO5_SEL = "CLKO5";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOPD_DLY = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_CPHASE = 3;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_DIV = 4;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_ENABLE = "ENABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_TRIM_DELAY = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOP_TRIM_POL = "RISING";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS2_CPHASE = 15;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS2_DIV = 16;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS2_ENABLE = "ENABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS2_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS3_CPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS3_DIV = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS3_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS3_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_CPHASE = 7;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_DIV = 8;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_ENABLE = "ENABLED";
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_FPHASE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_TRIM_DELAY = 0;
    defparam \PLL_25to200_1/PLLInst_0 .CLKOS_TRIM_POL = "RISING";
    defparam \PLL_25to200_1/PLLInst_0 .DCRST_ENA = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .DDRST_ENA = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .DPHASE_SOURCE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .EN_PHI = "FALSE";
    defparam \PLL_25to200_1/PLLInst_0 .FEEDBK_PATH = "INT_DIVA";
    defparam \PLL_25to200_1/PLLInst_0 .FRACN_DIV = 0;
    defparam \PLL_25to200_1/PLLInst_0 .FRACN_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .INTFB_WAKE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .MRST_ENA = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXA2 = "DIVA";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXB2 = "DIVB";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXC2 = "DIVC";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXD2 = "DIVD";
    defparam \PLL_25to200_1/PLLInst_0 .OUTDIVIDER_MUXE2 = "DIVE";
    defparam \PLL_25to200_1/PLLInst_0 .PLLRST_ENA = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .PLL_LOCK_MODE = 0;
    defparam \PLL_25to200_1/PLLInst_0 .PLL_USE_WB = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .PREDIVIDER_MUXA1 = 0;
    defparam \PLL_25to200_1/PLLInst_0 .PREDIVIDER_MUXB1 = 0;
    defparam \PLL_25to200_1/PLLInst_0 .PREDIVIDER_MUXC1 = 0;
    defparam \PLL_25to200_1/PLLInst_0 .PREDIVIDER_MUXD1 = 0;
    defparam \PLL_25to200_1/PLLInst_0 .STDBY_ENABLE = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_A0 = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_B0 = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_C0 = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_D0 = "DISABLED";
    defparam \PLL_25to200_1/PLLInst_0 .VCO_BYPASS_E0 = "DISABLED";

    xsXORCY \led_wf1/_i_6/bitAdd_1/xorcy 
    (
        .CI(\led_wf1/cnt [0]),
        .LI(\led_wf1/cnt [1]),
        .O(\led_wf1/n_35[1] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_1/muxcy 
    (
        .CI(\led_wf1/cnt [0]),
        .DI(\led_wf1/cnt [1]),
        .S(\led_wf1/cnt [1]),
        .O(\led_wf1/_i_6/_n_1 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_2/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_1 ),
        .LI(\led_wf1/cnt [2]),
        .O(\led_wf1/n_35[2] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_2/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_1 ),
        .DI(\led_wf1/cnt [2]),
        .S(\led_wf1/cnt [2]),
        .O(\led_wf1/_i_6/_n_3 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_3/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_3 ),
        .LI(\led_wf1/cnt [3]),
        .O(\led_wf1/n_35[3] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_3/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_3 ),
        .DI(\led_wf1/cnt [3]),
        .S(\led_wf1/cnt [3]),
        .O(\led_wf1/_i_6/_n_5 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_4/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_5 ),
        .LI(\led_wf1/cnt [4]),
        .O(\led_wf1/n_35[4] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_4/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_5 ),
        .DI(\led_wf1/cnt [4]),
        .S(\led_wf1/cnt [4]),
        .O(\led_wf1/_i_6/_n_7 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_5/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_7 ),
        .LI(\led_wf1/cnt [5]),
        .O(\led_wf1/n_35[5] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_5/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_7 ),
        .DI(\led_wf1/cnt [5]),
        .S(\led_wf1/cnt [5]),
        .O(\led_wf1/_i_6/_n_9 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_6/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_9 ),
        .LI(\led_wf1/cnt [6]),
        .O(\led_wf1/n_35[6] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_6/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_9 ),
        .DI(\led_wf1/cnt [6]),
        .S(\led_wf1/cnt [6]),
        .O(\led_wf1/_i_6/_n_11 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_7/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_11 ),
        .LI(\led_wf1/cnt [7]),
        .O(\led_wf1/n_35[7] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_7/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_11 ),
        .DI(\led_wf1/cnt [7]),
        .S(\led_wf1/cnt [7]),
        .O(\led_wf1/_i_6/_n_13 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_8/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_13 ),
        .LI(\led_wf1/cnt [8]),
        .O(\led_wf1/n_35[8] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_8/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_13 ),
        .DI(\led_wf1/cnt [8]),
        .S(\led_wf1/cnt [8]),
        .O(\led_wf1/_i_6/_n_15 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_9/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_15 ),
        .LI(\led_wf1/cnt [9]),
        .O(\led_wf1/n_35[9] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_9/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_15 ),
        .DI(\led_wf1/cnt [9]),
        .S(\led_wf1/cnt [9]),
        .O(\led_wf1/_i_6/_n_17 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_10/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_17 ),
        .LI(\led_wf1/cnt [10]),
        .O(\led_wf1/n_35[10] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_10/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_17 ),
        .DI(\led_wf1/cnt [10]),
        .S(\led_wf1/cnt [10]),
        .O(\led_wf1/_i_6/_n_19 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_11/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_19 ),
        .LI(\led_wf1/cnt [11]),
        .O(\led_wf1/n_35[11] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_11/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_19 ),
        .DI(\led_wf1/cnt [11]),
        .S(\led_wf1/cnt [11]),
        .O(\led_wf1/_i_6/_n_21 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_12/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_21 ),
        .LI(\led_wf1/cnt [12]),
        .O(\led_wf1/n_35[12] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_12/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_21 ),
        .DI(\led_wf1/cnt [12]),
        .S(\led_wf1/cnt [12]),
        .O(\led_wf1/_i_6/_n_23 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_13/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_23 ),
        .LI(\led_wf1/cnt [13]),
        .O(\led_wf1/n_35[13] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_13/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_23 ),
        .DI(\led_wf1/cnt [13]),
        .S(\led_wf1/cnt [13]),
        .O(\led_wf1/_i_6/_n_25 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_14/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_25 ),
        .LI(\led_wf1/cnt [14]),
        .O(\led_wf1/n_35[14] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_14/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_25 ),
        .DI(\led_wf1/cnt [14]),
        .S(\led_wf1/cnt [14]),
        .O(\led_wf1/_i_6/_n_27 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_15/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_27 ),
        .LI(\led_wf1/cnt [15]),
        .O(\led_wf1/n_35[15] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_15/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_27 ),
        .DI(\led_wf1/cnt [15]),
        .S(\led_wf1/cnt [15]),
        .O(\led_wf1/_i_6/_n_29 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_16/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_29 ),
        .LI(\led_wf1/cnt [16]),
        .O(\led_wf1/n_35[16] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_16/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_29 ),
        .DI(\led_wf1/cnt [16]),
        .S(\led_wf1/cnt [16]),
        .O(\led_wf1/_i_6/_n_31 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_17/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_31 ),
        .LI(\led_wf1/cnt [17]),
        .O(\led_wf1/n_35[17] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_17/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_31 ),
        .DI(\led_wf1/cnt [17]),
        .S(\led_wf1/cnt [17]),
        .O(\led_wf1/_i_6/_n_33 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_18/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_33 ),
        .LI(\led_wf1/cnt [18]),
        .O(\led_wf1/n_35[18] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_18/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_33 ),
        .DI(\led_wf1/cnt [18]),
        .S(\led_wf1/cnt [18]),
        .O(\led_wf1/_i_6/_n_35 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_19/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_35 ),
        .LI(\led_wf1/cnt [19]),
        .O(\led_wf1/n_35[19] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_19/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_35 ),
        .DI(\led_wf1/cnt [19]),
        .S(\led_wf1/cnt [19]),
        .O(\led_wf1/_i_6/_n_37 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_20/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_37 ),
        .LI(\led_wf1/cnt [20]),
        .O(\led_wf1/n_35[20] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_20/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_37 ),
        .DI(\led_wf1/cnt [20]),
        .S(\led_wf1/cnt [20]),
        .O(\led_wf1/_i_6/_n_39 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_21/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_39 ),
        .LI(\led_wf1/cnt [21]),
        .O(\led_wf1/n_35[21] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_21/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_39 ),
        .DI(\led_wf1/cnt [21]),
        .S(\led_wf1/cnt [21]),
        .O(\led_wf1/_i_6/_n_41 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_22/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_41 ),
        .LI(\led_wf1/cnt [22]),
        .O(\led_wf1/n_35[22] )
    );
    xsMUXCY \led_wf1/_i_6/bitAdd_22/muxcy 
    (
        .CI(\led_wf1/_i_6/_n_41 ),
        .DI(\led_wf1/cnt [22]),
        .S(\led_wf1/cnt [22]),
        .O(\led_wf1/_i_6/_n_43 )
    );
    xsXORCY \led_wf1/_i_6/bitAdd_23/xorcy 
    (
        .CI(\led_wf1/_i_6/_n_43 ),
        .LI(\led_wf1/cnt [23]),
        .O(\led_wf1/n_35[23] )
    );
    xsIOBI clk_25M_pad
    (
        .I(clk_25M),
        .O(clk_25M_c)
    );
    xsIOBI swdclk_pad
    (
        .I(swdclk),
        .O(swdclk_c)
    );
    xsIOBI \key_pin[1]_pad 
    (
        .I(key_pin[1]),
        .O(\key_pin[1]_c )
    );
    xsIOBI \key_pin[0]_pad 
    (
        .I(key_pin[0]),
        .O(\key_pin[0]_c )
    );
    xsIOBI uart_DAP_rx_pad
    (
        .I(uart_DAP_rx),
        .O(uart_DAP_rx_c)
    );
    xsIOBO led_core_pad
    (
        .I(led_core_c),
        .O(led_core)
    );
    xsIOBO \SRAM_ADDR[18]_pad 
    (
        .I(\SRAM_ADDR[18]_c ),
        .O(SRAM_ADDR[18])
    );
    xsIOBO \SRAM_ADDR[17]_pad 
    (
        .I(\SRAM_ADDR[17]_c ),
        .O(SRAM_ADDR[17])
    );
    xsIOBO \SRAM_ADDR[16]_pad 
    (
        .I(\SRAM_ADDR[16]_c ),
        .O(SRAM_ADDR[16])
    );
    xsIOBO \SRAM_ADDR[15]_pad 
    (
        .I(\SRAM_ADDR[15]_c ),
        .O(SRAM_ADDR[15])
    );
    xsIOBO \SRAM_ADDR[14]_pad 
    (
        .I(\SRAM_ADDR[14]_c ),
        .O(SRAM_ADDR[14])
    );
    xsIOBO \SRAM_ADDR[13]_pad 
    (
        .I(\SRAM_ADDR[13]_c ),
        .O(SRAM_ADDR[13])
    );
    xsIOBO \SRAM_ADDR[12]_pad 
    (
        .I(\SRAM_ADDR[12]_c ),
        .O(SRAM_ADDR[12])
    );
    xsIOBO \SRAM_ADDR[11]_pad 
    (
        .I(\SRAM_ADDR[11]_c ),
        .O(SRAM_ADDR[11])
    );
    xsIOBO \SRAM_ADDR[10]_pad 
    (
        .I(\SRAM_ADDR[10]_c ),
        .O(SRAM_ADDR[10])
    );
    xsIOBO \SRAM_ADDR[9]_pad 
    (
        .I(\SRAM_ADDR[9]_c ),
        .O(SRAM_ADDR[9])
    );
    xsIOBO \SRAM_ADDR[8]_pad 
    (
        .I(\SRAM_ADDR[8]_c ),
        .O(SRAM_ADDR[8])
    );
    xsIOBO \SRAM_ADDR[7]_pad 
    (
        .I(\SRAM_ADDR[7]_c ),
        .O(SRAM_ADDR[7])
    );
    xsIOBO \SRAM_ADDR[6]_pad 
    (
        .I(\SRAM_ADDR[6]_c ),
        .O(SRAM_ADDR[6])
    );
    xsIOBO \SRAM_ADDR[5]_pad 
    (
        .I(\SRAM_ADDR[5]_c ),
        .O(SRAM_ADDR[5])
    );
    xsIOBO \SRAM_ADDR[4]_pad 
    (
        .I(\SRAM_ADDR[4]_c ),
        .O(SRAM_ADDR[4])
    );
    xsIOBO \SRAM_ADDR[3]_pad 
    (
        .I(\SRAM_ADDR[3]_c ),
        .O(SRAM_ADDR[3])
    );
    xsIOBO \SRAM_ADDR[2]_pad 
    (
        .I(\SRAM_ADDR[2]_c ),
        .O(SRAM_ADDR[2])
    );
    xsIOBO \SRAM_ADDR[1]_pad 
    (
        .I(\SRAM_ADDR[1]_c ),
        .O(SRAM_ADDR[1])
    );
    xsIOBO \SRAM_ADDR[0]_pad 
    (
        .I(\SRAM_ADDR[0]_c ),
        .O(SRAM_ADDR[0])
    );
    xsIOBO SRAM_nWE_pad
    (
        .I(SRAM_nWE_c),
        .O(SRAM_nWE)
    );
    xsIOBO SRAM_nOE_pad
    (
        .I(SRAM_nOE_c),
        .O(SRAM_nOE)
    );
    xsIOBO SRAM_nCE_pad
    (
        .I(SRAM_nCE_c),
        .O(SRAM_nCE)
    );
    xsIOBO SRAM_nLB_pad
    (
        .I(SRAM_nLB_c),
        .O(SRAM_nLB)
    );
    xsIOBO SRAM_nUB_pad
    (
        .I(SRAM_nUB_c),
        .O(SRAM_nUB)
    );
    xsIOBO flash_sclk_pad
    (
        .I(n_GND_c),
        .O(flash_sclk)
    );
    xsIOBO flash_cs_pad
    (
        .I(n_VCC_c),
        .O(flash_cs)
    );
    xsIOBO flash_mosi_pad
    (
        .I(n_GND_c),
        .O(flash_mosi)
    );
    xsIOBO \led_pin[3]_pad 
    (
        .I(\led_pin[3]_c ),
        .O(led_pin[3])
    );
    xsIOBO \led_pin[2]_pad 
    (
        .I(\led_pin[2]_c ),
        .O(led_pin[2])
    );
    xsIOBO \led_pin[1]_pad 
    (
        .I(\led_pin[1]_c ),
        .O(led_pin[1])
    );
    xsIOBO \led_pin[0]_pad 
    (
        .I(osc_c6_pin_c),
        .O(led_pin[0])
    );
    xsIOBO beep_pin_pad
    (
        .I(beep_pin_c),
        .O(beep_pin)
    );
    xsIOBO uart_DAP_tx_pad
    (
        .I(uart_DAP_tx_c),
        .O(uart_DAP_tx)
    );
    xsIOBO uart_ch340_tx_pad
    (
        .I(n_GND_c),
        .O(uart_ch340_tx)
    );
    xsIOBO sd_sclk_pad
    (
        .I(n_GND_c),
        .O(sd_sclk)
    );
    xsIOBO sd_cs_pad
    (
        .I(n_VCC_c),
        .O(sd_cs)
    );
    xsIOBO sd_mosi_pad
    (
        .I(n_GND_c),
        .O(sd_mosi)
    );
    xsIOBO w5500_sclk_pad
    (
        .I(n_GND_c),
        .O(w5500_sclk)
    );
    xsIOBO w5500_cs_pad
    (
        .I(n_VCC_c),
        .O(w5500_cs)
    );
    xsIOBO w5500_mosi_pad
    (
        .I(n_GND_c),
        .O(w5500_mosi)
    );
    xsIOBO seg7_SH_CP_pad
    (
        .I(n_GND_c),
        .O(seg7_SH_CP)
    );
    xsIOBO seg7_ST_CP_pad
    (
        .I(n_VCC_c),
        .O(seg7_ST_CP)
    );
    xsIOBO seg7_DS_pad
    (
        .I(n_GND_c),
        .O(seg7_DS)
    );
    xsIOBO osc_c6_pin_pad
    (
        .I(osc_c6_pin_c),
        .O(osc_c6_pin)
    );
    xsIOBB \SRAM_DQ[15]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [15]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1119_combout),
        .B(SRAM_DQ[15])
    );
    xsIOBB \SRAM_DQ[14]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [14]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1120_combout),
        .B(SRAM_DQ[14])
    );
    xsIOBB \SRAM_DQ[13]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [13]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1121_combout),
        .B(SRAM_DQ[13])
    );
    xsIOBB \SRAM_DQ[12]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [12]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1122_combout),
        .B(SRAM_DQ[12])
    );
    xsIOBB \SRAM_DQ[11]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [11]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1123_combout),
        .B(SRAM_DQ[11])
    );
    xsIOBB \SRAM_DQ[10]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [10]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1124_combout),
        .B(SRAM_DQ[10])
    );
    xsIOBB \SRAM_DQ[9]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [9]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1125_combout),
        .B(SRAM_DQ[9])
    );
    xsIOBB \SRAM_DQ[8]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [8]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1126_combout),
        .B(SRAM_DQ[8])
    );
    xsIOBB \SRAM_DQ[7]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [7]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1127_combout),
        .B(SRAM_DQ[7])
    );
    xsIOBB \SRAM_DQ[6]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [6]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1128_combout),
        .B(SRAM_DQ[6])
    );
    xsIOBB \SRAM_DQ[5]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [5]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1129_combout),
        .B(SRAM_DQ[5])
    );
    xsIOBB \SRAM_DQ[4]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [4]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1130_combout),
        .B(SRAM_DQ[4])
    );
    xsIOBB \SRAM_DQ[3]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [3]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1131_combout),
        .B(SRAM_DQ[3])
    );
    xsIOBB \SRAM_DQ[2]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [2]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1132_combout),
        .B(SRAM_DQ[2])
    );
    xsIOBB \SRAM_DQ[1]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [1]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1133_combout),
        .B(SRAM_DQ[1])
    );
    xsIOBB \SRAM_DQ[0]_pad 
    (
        .I(\cm3inst/ahb_sram1/DATAOUT [0]),
        .T(\cm3inst/ahb_sram1/DATAOEn ),
        .O(_n_1134_combout),
        .B(SRAM_DQ[0])
    );
    xsIOBB swddio_pad
    (
        .I(\cm3inst/TMSO ),
        .T(\cm3inst/TMSOEN ),
        .O(_n_1135_combout),
        .B(swddio)
    );
    xsDFFSA_K1C1E1 \led_wf1/led_sig_reg[0] 
    (
        .C(clk_25M_c),
        .CE(_n_1089),
        .CLR(\led_wf1/n_3 ),
        .D(\led_pin[1]_c ),
        .Q(osc_c6_pin_c)
    );
    defparam \led_wf1/led_sig_reg[0] .INIT = 1'B0;

    xsDFFSA_K1C1E1 \led_wf1/led_sig_reg[1] 
    (
        .C(clk_25M_c),
        .CE(_n_1089),
        .CLR(\led_wf1/n_3 ),
        .D(\led_pin[2]_c ),
        .Q(\led_pin[1]_c )
    );
    defparam \led_wf1/led_sig_reg[1] .INIT = 1'B0;

    xsDFFSA_K1P1E1 \led_wf1/led_sig_reg[2] 
    (
        .C(clk_25M_c),
        .CE(_n_1089),
        .D(\led_pin[3]_c ),
        .PRE(\led_wf1/n_3 ),
        .Q(\led_pin[2]_c )
    );
    defparam \led_wf1/led_sig_reg[2] .INIT = 1'B1;

    xsDFFSA_K1P1E1 \led_wf1/led_sig_reg[3] 
    (
        .C(clk_25M_c),
        .CE(_n_1089),
        .D(osc_c6_pin_c),
        .PRE(\led_wf1/n_3 ),
        .Q(\led_pin[3]_c )
    );
    defparam \led_wf1/led_sig_reg[3] .INIT = 1'B1;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[23] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_34 ),
        .Q(\led_wf1/cnt [23])
    );
    defparam \led_wf1/cnt_reg[23] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[22] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_33 ),
        .Q(\led_wf1/cnt [22])
    );
    defparam \led_wf1/cnt_reg[22] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[21] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_32 ),
        .Q(\led_wf1/cnt [21])
    );
    defparam \led_wf1/cnt_reg[21] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[20] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_31 ),
        .Q(\led_wf1/cnt [20])
    );
    defparam \led_wf1/cnt_reg[20] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[19] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_30 ),
        .Q(\led_wf1/cnt [19])
    );
    defparam \led_wf1/cnt_reg[19] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[18] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_29 ),
        .Q(\led_wf1/cnt [18])
    );
    defparam \led_wf1/cnt_reg[18] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[17] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_28 ),
        .Q(\led_wf1/cnt [17])
    );
    defparam \led_wf1/cnt_reg[17] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[16] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_27 ),
        .Q(\led_wf1/cnt [16])
    );
    defparam \led_wf1/cnt_reg[16] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[15] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_26 ),
        .Q(\led_wf1/cnt [15])
    );
    defparam \led_wf1/cnt_reg[15] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[14] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_25 ),
        .Q(\led_wf1/cnt [14])
    );
    defparam \led_wf1/cnt_reg[14] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[13] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_24 ),
        .Q(\led_wf1/cnt [13])
    );
    defparam \led_wf1/cnt_reg[13] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[12] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_23 ),
        .Q(\led_wf1/cnt [12])
    );
    defparam \led_wf1/cnt_reg[12] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[11] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_22 ),
        .Q(\led_wf1/cnt [11])
    );
    defparam \led_wf1/cnt_reg[11] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[10] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_21 ),
        .Q(\led_wf1/cnt [10])
    );
    defparam \led_wf1/cnt_reg[10] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[9] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_20 ),
        .Q(\led_wf1/cnt [9])
    );
    defparam \led_wf1/cnt_reg[9] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[8] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_19 ),
        .Q(\led_wf1/cnt [8])
    );
    defparam \led_wf1/cnt_reg[8] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[7] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_18 ),
        .Q(\led_wf1/cnt [7])
    );
    defparam \led_wf1/cnt_reg[7] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[6] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_17 ),
        .Q(\led_wf1/cnt [6])
    );
    defparam \led_wf1/cnt_reg[6] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[5] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_16 ),
        .Q(\led_wf1/cnt [5])
    );
    defparam \led_wf1/cnt_reg[5] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[4] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_15 ),
        .Q(\led_wf1/cnt [4])
    );
    defparam \led_wf1/cnt_reg[4] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[3] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_14 ),
        .Q(\led_wf1/cnt [3])
    );
    defparam \led_wf1/cnt_reg[3] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[2] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_13 ),
        .Q(\led_wf1/cnt [2])
    );
    defparam \led_wf1/cnt_reg[2] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[1] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_12 ),
        .Q(\led_wf1/cnt [1])
    );
    defparam \led_wf1/cnt_reg[1] .INIT = 1'B0;

    xsDFFSA_K1C1 \led_wf1/cnt_reg[0] 
    (
        .C(clk_25M_c),
        .CLR(\led_wf1/n_3 ),
        .D(\led_wf1/n_11 ),
        .Q(\led_wf1/cnt [0])
    );
    defparam \led_wf1/cnt_reg[0] .INIT = 1'B0;

    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_size_reg[1] 
    (
        .C(clk_100M),
        .CE(\cm3inst/TARGEXP0HREADYMUX ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HSIZE [1]),
        .Q(\cm3inst/ahb_sram1/reg_size [1])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[0] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[0] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [0])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[1] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[1] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [1])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[2] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[2] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [2])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[3] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[3] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [3])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[4] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[4] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [4])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[5] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[5] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [5])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[6] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[6] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [6])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[7] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[7] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [7])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[8] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[8] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [8])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[9] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[9] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [9])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[10] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[10] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [10])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[11] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[11] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [11])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[12] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[12] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [12])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[13] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[13] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [13])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[14] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[14] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [14])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/DATAOUT_reg[15] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/reg_active ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/i_dataout[15] ),
        .Q(\cm3inst/ahb_sram1/DATAOUT [15])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_0_reg[0] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_132 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1134_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_0 [0])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_0_reg[1] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_132 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1133_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_0 [1])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_0_reg[2] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_132 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1132_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_0 [2])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_0_reg[3] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_132 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1131_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_0 [3])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_0_reg[4] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_132 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1130_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_0 [4])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_0_reg[5] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_132 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1129_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_0 [5])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_0_reg[6] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_132 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1128_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_0 [6])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_0_reg[7] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_132 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1127_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_0 [7])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_1_reg[0] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_135 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1126_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_1 [0])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_1_reg[1] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_135 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1125_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_1 [1])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_1_reg[2] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_135 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1124_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_1 [2])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_1_reg[3] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_135 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1123_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_1 [3])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_1_reg[4] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_135 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1122_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_1 [4])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_1_reg[5] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_135 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1121_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_1 [5])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_1_reg[6] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_135 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1120_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_1 [6])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/read_buffer_1_reg[7] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_135 ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(_n_1119_combout),
        .Q(\cm3inst/ahb_sram1/read_buffer_1 [7])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_active_reg 
    (
        .C(clk_100M),
        .CE(\cm3inst/TARGEXP0HREADYMUX ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/trans_valid ),
        .Q(\cm3inst/ahb_sram1/reg_active )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_write_reg 
    (
        .C(clk_100M),
        .CE(\cm3inst/TARGEXP0HREADYMUX ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HWRITE ),
        .Q(\cm3inst/ahb_sram1/reg_write )
    );
    xsDFFSA_K1C1 \cm3inst/ahb_sram1/last_operation_reg 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/last_operation_reg_ctrl_din ),
        .Q(\cm3inst/ahb_sram1/last_operation )
    );
    xsDFFSA_K1C1 \cm3inst/ahb_sram1/reg_addr_low_reg[1] 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/nxt_addr_low[1] ),
        .Q(\SRAM_ADDR[0]_c )
    );
    xsDFFSA_K1C1 \cm3inst/ahb_sram1/reg_lb_mux_reg[1] 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/nxt_lb_mux[1] ),
        .Q(\cm3inst/ahb_sram1/reg_lb_mux [1])
    );
    xsDFFSA_K1C1 \cm3inst/ahb_sram1/reg_ub_mux_reg[1] 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/nxt_ub_mux[1] ),
        .Q(\cm3inst/ahb_sram1/reg_ub_mux [1])
    );
    xsDFFSA_K1C1 \cm3inst/ahb_sram1/reg_rd_req_reg 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/RDREQ ),
        .Q(\cm3inst/ahb_sram1/reg_rd_req )
    );
    xsDFFSA_K1C1 \cm3inst/ahb_sram1/reg_wr_req_reg 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/WRREQ ),
        .Q(\cm3inst/ahb_sram1/reg_wr_req )
    );
    xsDFFSA_K1P1 \cm3inst/ahb_sram1/reg_bs_n_reg[0] 
    (
        .C(clk_100M),
        .D(\cm3inst/ahb_sram1/nxt_bs_n [0]),
        .PRE(\cm3inst/ahb_sram1/n_53 ),
        .Q(SRAM_nLB_c)
    );
    xsDFFSA_K1P1 \cm3inst/ahb_sram1/reg_bs_n_reg[1] 
    (
        .C(clk_100M),
        .D(\cm3inst/ahb_sram1/nxt_bs_n [1]),
        .PRE(\cm3inst/ahb_sram1/n_53 ),
        .Q(SRAM_nUB_c)
    );
    xsDFFSA_K1P1 \cm3inst/ahb_sram1/reg_ce_n_reg 
    (
        .C(clk_100M),
        .D(\cm3inst/ahb_sram1/nxt_ce_n ),
        .PRE(\cm3inst/ahb_sram1/n_53 ),
        .Q(SRAM_nCE_c)
    );
    xsDFFSA_K1P1 \cm3inst/ahb_sram1/reg_dataoe_n_reg 
    (
        .C(clk_100M),
        .D(\cm3inst/ahb_sram1/nxt_dataoe_n ),
        .PRE(\cm3inst/ahb_sram1/n_53 ),
        .Q(\cm3inst/ahb_sram1/DATAOEn )
    );
    xsDFFSA_K1P1 \cm3inst/ahb_sram1/reg_oe_n_reg 
    (
        .C(clk_100M),
        .D(\cm3inst/ahb_sram1/nxt_oe_n ),
        .PRE(\cm3inst/ahb_sram1/n_53 ),
        .Q(SRAM_nOE_c)
    );
    xsDFFSA_K1P1 \cm3inst/ahb_sram1/reg_we_n_reg 
    (
        .C(clk_100M),
        .D(\cm3inst/ahb_sram1/nxt_we_n ),
        .PRE(\cm3inst/ahb_sram1/n_53 ),
        .Q(SRAM_nWE_c)
    );
    xsDFFSA_K1C1 \cm3inst/ahb_sram1/reg_mstate_reg_1 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/n_211 ),
        .Q(\cm3inst/ahb_sram1/n_198 )
    );
    defparam \cm3inst/ahb_sram1/reg_mstate_reg_1 .INIT = 1'B0;

    xsDFFSA_K1P1 \cm3inst/ahb_sram1/reg_bstate_reg_2 
    (
        .C(clk_100M),
        .D(\cm3inst/ahb_sram1/n_195 ),
        .PRE(\cm3inst/ahb_sram1/n_53 ),
        .Q(\cm3inst/ahb_sram1/n_162 )
    );
    defparam \cm3inst/ahb_sram1/reg_bstate_reg_2 .INIT = 1'B1;

    xsDFFSA_K1P1 \cm3inst/ahb_sram1/reg_mstate_reg_0 
    (
        .C(clk_100M),
        .D(\cm3inst/ahb_sram1/n_208 ),
        .PRE(\cm3inst/ahb_sram1/n_53 ),
        .Q(\cm3inst/ahb_sram1/n_206 )
    );
    defparam \cm3inst/ahb_sram1/reg_mstate_reg_0 .INIT = 1'B1;

    xsDFFSA_K1P1 \cm3inst/ahb_sram1/reg_mstate_reg_2 
    (
        .C(clk_100M),
        .D(\cm3inst/ahb_sram1/n_218 ),
        .PRE(\cm3inst/ahb_sram1/n_53 ),
        .Q(\cm3inst/ahb_sram1/n_201 )
    );
    defparam \cm3inst/ahb_sram1/reg_mstate_reg_2 .INIT = 1'B1;

    xsDFFSA_K1C1 \cm3inst/ahb_sram1/reg_mcount_reg[2] 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/n_156 ),
        .Q(\cm3inst/ahb_sram1/reg_mcount [2])
    );
    xsDFFSA_K1C1 \cm3inst/ahb_sram1/reg_mcount_reg[1] 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/n_155 ),
        .Q(\cm3inst/ahb_sram1/reg_mcount [1])
    );
    xsDFFSA_K1C1 \cm3inst/ahb_sram1/reg_mcount_reg[0] 
    (
        .C(clk_100M),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/n_154 ),
        .Q(\cm3inst/ahb_sram1/reg_mcount [0])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[0] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [2]),
        .Q(\SRAM_ADDR[1]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[1] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [3]),
        .Q(\SRAM_ADDR[2]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[2] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [4]),
        .Q(\SRAM_ADDR[3]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[3] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [5]),
        .Q(\SRAM_ADDR[4]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[4] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [6]),
        .Q(\SRAM_ADDR[5]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[5] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [7]),
        .Q(\SRAM_ADDR[6]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[6] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [8]),
        .Q(\SRAM_ADDR[7]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[7] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [9]),
        .Q(\SRAM_ADDR[8]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[8] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [10]),
        .Q(\SRAM_ADDR[9]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[9] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [11]),
        .Q(\SRAM_ADDR[10]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[10] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [12]),
        .Q(\SRAM_ADDR[11]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[11] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [13]),
        .Q(\SRAM_ADDR[12]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[12] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [14]),
        .Q(\SRAM_ADDR[13]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[13] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [15]),
        .Q(\SRAM_ADDR[14]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[14] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [16]),
        .Q(\SRAM_ADDR[15]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[15] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [17]),
        .Q(\SRAM_ADDR[16]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[16] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [18]),
        .Q(\SRAM_ADDR[17]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_addr_high_reg[17] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/TARGEXP0HADDR [19]),
        .Q(\SRAM_ADDR[18]_c )
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_byte_mask_reg[0] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/n_120 ),
        .Q(\cm3inst/ahb_sram1/reg_byte_mask [0])
    );
    xsDFFSA_K1C1E1 \cm3inst/ahb_sram1/reg_byte_mask_reg[1] 
    (
        .C(clk_100M),
        .CE(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .CLR(\cm3inst/ahb_sram1/n_53 ),
        .D(\cm3inst/ahb_sram1/n_122 ),
        .Q(\cm3inst/ahb_sram1/reg_byte_mask [1])
    );
    xsLUTSA2 \cm3inst/ahb_sram1/_i_307 
    (
        .I0(\cm3inst/ahb_sram1/reg_mcount [0]),
        .I1(net_extracted_nHQX1),
        .O(\cm3inst/ahb_sram1/n_154 )
    );
    defparam \cm3inst/ahb_sram1/_i_307 .INIT = 4'H4;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_312 
    (
        .I0(\cm3inst/ahb_sram1/n_206 ),
        .I1(\cm3inst/ahb_sram1/reg_mcount [2]),
        .I2(\cm3inst/ahb_sram1/reg_mcount [1]),
        .I3(\cm3inst/ahb_sram1/reg_mcount [0]),
        .I4(\cm3inst/ahb_sram1/DONE ),
        .I5(_n_1091),
        .O(\cm3inst/ahb_sram1/n_155 )
    );
    defparam \cm3inst/ahb_sram1/_i_312 .INIT = 64'HFFFFFFFFFFFFF55D;

    xsLUTSA6 \dec_of_cm3inst/ahb_sram1/_i_312 
    (
        .I0(\cm3inst/ahb_sram1/last_operation ),
        .I1(\cm3inst/ahb_sram1/n_198 ),
        .I2(\cm3inst/ahb_sram1/n_201 ),
        .I3(\cm3inst/ahb_sram1/n_97 ),
        .I4(\cm3inst/ahb_sram1/RDREQ ),
        .I5(\cm3inst/ahb_sram1/WRREQ ),
        .O(_n_1091)
    );
    defparam \dec_of_cm3inst/ahb_sram1/_i_312 .INIT = 64'H1033203010330000;

    xsLUTSA4 \cm3inst/ahb_sram1/_i_316 
    (
        .I0(\cm3inst/ahb_sram1/reg_mcount [2]),
        .I1(\cm3inst/ahb_sram1/reg_mcount [1]),
        .I2(\cm3inst/ahb_sram1/reg_mcount [0]),
        .I3(net_extracted_nHQX1),
        .O(\cm3inst/ahb_sram1/n_156 )
    );
    defparam \cm3inst/ahb_sram1/_i_316 .INIT = 16'HA900;

    xsLUTSA6 inst_extracted_iHQX1
    (
        .I0(\cm3inst/ahb_sram1/last_operation ),
        .I1(\cm3inst/ahb_sram1/n_97 ),
        .I2(\cm3inst/ahb_sram1/RDREQ ),
        .I3(\cm3inst/ahb_sram1/WRREQ ),
        .I4(net_extracted_nHQX15),
        .I5(\cm3inst/ahb_sram1/_i_307_decomp ),
        .O(net_extracted_nHQX1)
    );
    defparam inst_extracted_iHQX1.INIT = 64'HCCCCCCCC848C0000;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_176 
    (
        .I0(\cm3inst/ahb_sram1/last_operation ),
        .I1(\cm3inst/ahb_sram1/n_198 ),
        .I2(\cm3inst/ahb_sram1/n_206 ),
        .I3(\cm3inst/ahb_sram1/n_201 ),
        .I4(\cm3inst/ahb_sram1/n_97 ),
        .I5(\cm3inst/ahb_sram1/RDREQ ),
        .O(\cm3inst/ahb_sram1/n_218 )
    );
    defparam \cm3inst/ahb_sram1/_i_176 .INIT = 64'HEFCF0FCFFFCF3FFF;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_165 
    (
        .I0(\cm3inst/ahb_sram1/n_198 ),
        .I1(\cm3inst/ahb_sram1/n_206 ),
        .I2(\cm3inst/ahb_sram1/n_201 ),
        .I3(\cm3inst/ahb_sram1/RDREQ ),
        .I4(\cm3inst/ahb_sram1/WRREQ ),
        .I5(\cm3inst/ahb_sram1/n_100 ),
        .O(\cm3inst/ahb_sram1/n_208 )
    );
    defparam \cm3inst/ahb_sram1/_i_165 .INIT = 64'HF7F7FFFFF7B7FFFF;

    xsLUTSA2 \cm3inst/ahb_sram1/_i_307_decomp:0 
    (
        .I0(\cm3inst/ahb_sram1/n_198 ),
        .I1(\cm3inst/ahb_sram1/n_201 ),
        .O(\cm3inst/ahb_sram1/_i_307_decomp )
    );
    defparam \cm3inst/ahb_sram1/_i_307_decomp:0 .INIT = 4'H9;

    xsLUTSA5 \cm3inst/ahb_sram1/_i_151 
    (
        .I0(\cm3inst/TARGEXP0HSIZE [1]),
        .I1(\cm3inst/TARGEXP0HSIZE [0]),
        .I2(\cm3inst/ahb_sram1/n_162 ),
        .I3(\cm3inst/ahb_sram1/DONE ),
        .I4(\cm3inst/ahb_sram1/trans_valid ),
        .O(\cm3inst/ahb_sram1/n_195 )
    );
    defparam \cm3inst/ahb_sram1/_i_151 .INIT = 32'HDFD0FFF0;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_168 
    (
        .I0(\cm3inst/ahb_sram1/n_198 ),
        .I1(\cm3inst/ahb_sram1/n_206 ),
        .I2(\cm3inst/ahb_sram1/n_201 ),
        .O(\cm3inst/ahb_sram1/n_211 )
    );
    defparam \cm3inst/ahb_sram1/_i_168 .INIT = 8'H90;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_194 
    (
        .I0(\cm3inst/ahb_sram1/n_198 ),
        .I1(\cm3inst/ahb_sram1/n_206 ),
        .I2(\cm3inst/ahb_sram1/n_201 ),
        .I3(\cm3inst/ahb_sram1/reg_mcount [2]),
        .I4(\cm3inst/ahb_sram1/reg_mcount [1]),
        .I5(\cm3inst/ahb_sram1/reg_mcount [0]),
        .O(\cm3inst/ahb_sram1/nxt_we_n )
    );
    defparam \cm3inst/ahb_sram1/_i_194 .INIT = 64'H4F4F4F4F4F4F4FEF;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_191 
    (
        .I0(\cm3inst/ahb_sram1/last_operation ),
        .I1(\cm3inst/ahb_sram1/n_198 ),
        .I2(\cm3inst/ahb_sram1/n_206 ),
        .I3(\cm3inst/ahb_sram1/n_201 ),
        .I4(\cm3inst/ahb_sram1/n_97 ),
        .I5(\cm3inst/ahb_sram1/RDREQ ),
        .O(\cm3inst/ahb_sram1/nxt_oe_n )
    );
    defparam \cm3inst/ahb_sram1/_i_191 .INIT = 64'HEFCFCFCFFFCFFFFF;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_187 
    (
        .I0(\cm3inst/ahb_sram1/n_198 ),
        .I1(\cm3inst/ahb_sram1/n_206 ),
        .I2(\cm3inst/ahb_sram1/n_201 ),
        .I3(\cm3inst/ahb_sram1/RDREQ ),
        .I4(\cm3inst/ahb_sram1/WRREQ ),
        .I5(\cm3inst/ahb_sram1/n_100 ),
        .O(\cm3inst/ahb_sram1/nxt_dataoe_n )
    );
    defparam \cm3inst/ahb_sram1/_i_187 .INIT = 64'H45454F4F45054F4F;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_198 
    (
        .I0(\cm3inst/TARGEXP0HADDR [0]),
        .I1(\cm3inst/TARGEXP0HSIZE [1]),
        .I2(\cm3inst/TARGEXP0HSIZE [0]),
        .I3(\cm3inst/ahb_sram1/reg_byte_mask [1]),
        .I4(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .I5(\cm3inst/ahb_sram1/nxt_ce_n ),
        .O(\cm3inst/ahb_sram1/nxt_bs_n [1])
    );
    defparam \cm3inst/ahb_sram1/_i_198 .INIT = 64'HFFFFFFFF010100FF;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_341 
    (
        .I0(\cm3inst/TARGEXP0HADDR [0]),
        .I1(\cm3inst/TARGEXP0HSIZE [1]),
        .I2(\cm3inst/TARGEXP0HSIZE [0]),
        .O(\cm3inst/ahb_sram1/n_122 )
    );
    defparam \cm3inst/ahb_sram1/_i_341 .INIT = 8'HFE;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_196 
    (
        .I0(\cm3inst/TARGEXP0HADDR [0]),
        .I1(\cm3inst/TARGEXP0HSIZE [1]),
        .I2(\cm3inst/TARGEXP0HSIZE [0]),
        .I3(\cm3inst/ahb_sram1/reg_byte_mask [0]),
        .I4(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .I5(\cm3inst/ahb_sram1/nxt_ce_n ),
        .O(\cm3inst/ahb_sram1/nxt_bs_n [0])
    );
    defparam \cm3inst/ahb_sram1/_i_196 .INIT = 64'HFFFFFFFF020200FF;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_339 
    (
        .I0(\cm3inst/TARGEXP0HADDR [0]),
        .I1(\cm3inst/TARGEXP0HSIZE [1]),
        .I2(\cm3inst/TARGEXP0HSIZE [0]),
        .O(\cm3inst/ahb_sram1/n_120 )
    );
    defparam \cm3inst/ahb_sram1/_i_339 .INIT = 8'HFD;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_182 
    (
        .I0(\cm3inst/ahb_sram1/n_119 ),
        .I1(\cm3inst/ahb_sram1/RDREQ ),
        .I2(\cm3inst/ahb_sram1/WRREQ ),
        .I3(net_extracted_nHQX15),
        .I4(\cm3inst/ahb_sram1/_i_182_decomp ),
        .I5(net_extracted_nHQX4),
        .O(\cm3inst/ahb_sram1/nxt_ce_n )
    );
    defparam \cm3inst/ahb_sram1/_i_182 .INIT = 64'HFF3BCE0A3B3B0A0A;

    xsLUTSA4 inst_extracted_iHQX2
    (
        .I0(\cm3inst/ahb_sram1/last_operation ),
        .I1(\cm3inst/ahb_sram1/reg_mcount [2]),
        .I2(\cm3inst/ahb_sram1/reg_mcount [1]),
        .I3(\cm3inst/ahb_sram1/reg_mcount [0]),
        .O(net_extracted_nHQX4)
    );
    defparam inst_extracted_iHQX2.INIT = 16'HAAA8;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_182_decomp:0 
    (
        .I0(\cm3inst/ahb_sram1/last_operation ),
        .I1(\cm3inst/ahb_sram1/n_198 ),
        .I2(\cm3inst/ahb_sram1/n_206 ),
        .I3(\cm3inst/ahb_sram1/n_201 ),
        .I4(\cm3inst/ahb_sram1/n_97 ),
        .I5(\cm3inst/ahb_sram1/WRREQ ),
        .O(\cm3inst/ahb_sram1/_i_182_decomp )
    );
    defparam \cm3inst/ahb_sram1/_i_182_decomp:0 .INIT = 64'H1000003330003033;

    xsLUTSA3 inst_extracted_iHQX15
    (
        .I0(\cm3inst/ahb_sram1/n_198 ),
        .I1(\cm3inst/ahb_sram1/n_206 ),
        .I2(\cm3inst/ahb_sram1/n_201 ),
        .O(net_extracted_nHQX15)
    );
    defparam inst_extracted_iHQX15.INIT = 8'H40;

    xsLUTSA4 \cm3inst/ahb_sram1/_i_34 
    (
        .I0(\cm3inst/ahb_sram1/last_operation ),
        .I1(\cm3inst/ahb_sram1/reg_mcount [2]),
        .I2(\cm3inst/ahb_sram1/reg_mcount [1]),
        .I3(\cm3inst/ahb_sram1/reg_mcount [0]),
        .O(\cm3inst/ahb_sram1/n_100 )
    );
    defparam \cm3inst/ahb_sram1/_i_34 .INIT = 16'H5554;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_214/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWRITE ),
        .I1(\cm3inst/ahb_sram1/reg_write ),
        .I2(\cm3inst/ahb_sram1/reg_wr_req ),
        .I3(\cm3inst/ahb_sram1/n_162 ),
        .I4(\cm3inst/ahb_sram1/DONE ),
        .I5(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .O(\cm3inst/ahb_sram1/WRREQ )
    );
    defparam \cm3inst/ahb_sram1/_i_214/_i_0 .INIT = 64'HAAEEAAEE00CCF0CC;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_212/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWRITE ),
        .I1(\cm3inst/ahb_sram1/reg_write ),
        .I2(\cm3inst/ahb_sram1/reg_rd_req ),
        .I3(\cm3inst/ahb_sram1/n_162 ),
        .I4(\cm3inst/ahb_sram1/DONE ),
        .I5(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .O(\cm3inst/ahb_sram1/RDREQ )
    );
    defparam \cm3inst/ahb_sram1/_i_212/_i_0 .INIT = 64'H557755770033F033;

    xsLUTSA5 \cm3inst/ahb_sram1/_i_232/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HADDR [1]),
        .I1(\cm3inst/ahb_sram1/reg_ub_mux [1]),
        .I2(\cm3inst/ahb_sram1/n_162 ),
        .I3(\cm3inst/ahb_sram1/DONE ),
        .I4(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .O(\cm3inst/ahb_sram1/nxt_ub_mux[1] )
    );
    defparam \cm3inst/ahb_sram1/_i_232/_i_0 .INIT = 32'HAFAACFCC;

    xsLUTSA5 \cm3inst/ahb_sram1/_i_230/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HADDR [1]),
        .I1(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .I2(\cm3inst/ahb_sram1/n_162 ),
        .I3(\cm3inst/ahb_sram1/DONE ),
        .I4(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .O(\cm3inst/ahb_sram1/nxt_lb_mux[1] )
    );
    defparam \cm3inst/ahb_sram1/_i_230/_i_0 .INIT = 32'HAFAACFCC;

    xsLUTSA5 \cm3inst/ahb_sram1/_i_224/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HADDR [1]),
        .I1(\SRAM_ADDR[0]_c ),
        .I2(\cm3inst/ahb_sram1/n_162 ),
        .I3(\cm3inst/ahb_sram1/DONE ),
        .I4(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O ),
        .O(\cm3inst/ahb_sram1/nxt_addr_low[1] )
    );
    defparam \cm3inst/ahb_sram1/_i_224/_i_0 .INIT = 32'HAFAACFCC;

    xsLUTSA4 _i_13
    (
        .I0(\cm3inst/TARGEXP0HREADYMUX ),
        .I1(\cm3inst/TARGEXP0HSEL ),
        .I2(\cm3inst/TARGEXP0HTRANS [1]),
        .I3(\cm3inst/ahb_sram1/n_162 ),
        .O(\cm3inst/ahb_sram1/n_246_CE_AND_O_CE_AND_O )
    );
    defparam _i_13.INIT = 16'H8000;

    xsLUTSA6 \cm3inst/ahb_sram1/last_operation_reg_ctrlmux 
    (
        .I0(\cm3inst/ahb_sram1/last_operation ),
        .I1(\cm3inst/ahb_sram1/n_198 ),
        .I2(\cm3inst/ahb_sram1/n_201 ),
        .I3(\cm3inst/ahb_sram1/reg_mcount [2]),
        .I4(\cm3inst/ahb_sram1/reg_mcount [1]),
        .I5(\cm3inst/ahb_sram1/reg_mcount [0]),
        .O(\cm3inst/ahb_sram1/last_operation_reg_ctrl_din )
    );
    defparam \cm3inst/ahb_sram1/last_operation_reg_ctrlmux .INIT = 64'HAEAEAEAEAEAEAEAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_3 
    (
        .I0(\cm3inst/TARGEXP0HREADYMUX ),
        .I1(\cm3inst/TARGEXP0HSEL ),
        .I2(\cm3inst/TARGEXP0HTRANS [1]),
        .O(\cm3inst/ahb_sram1/trans_valid )
    );
    defparam \cm3inst/ahb_sram1/_i_3 .INIT = 8'H80;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_82 
    (
        .I0(\cm3inst/ahb_sram1/reg_active ),
        .I1(\cm3inst/ahb_sram1/reg_write ),
        .I2(\cm3inst/ahb_sram1/n_198 ),
        .I3(\cm3inst/ahb_sram1/n_162 ),
        .I4(\cm3inst/ahb_sram1/n_201 ),
        .I5(\cm3inst/ahb_sram1/n_97 ),
        .O(\cm3inst/ahb_sram1/n_135 )
    );
    defparam \cm3inst/ahb_sram1/_i_82 .INIT = 64'H0000002000000022;

    xsLUTSA6 \cm3inst/ahb_sram1/_i_79 
    (
        .I0(\cm3inst/ahb_sram1/reg_active ),
        .I1(\cm3inst/ahb_sram1/reg_write ),
        .I2(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .I3(\cm3inst/ahb_sram1/n_198 ),
        .I4(\cm3inst/ahb_sram1/n_201 ),
        .I5(\cm3inst/ahb_sram1/n_97 ),
        .O(\cm3inst/ahb_sram1/n_132 )
    );
    defparam \cm3inst/ahb_sram1/_i_79 .INIT = 64'H0000020000000202;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_78/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [31]),
        .I1(\cm3inst/TARGEXP0HWDATA [15]),
        .I2(\cm3inst/ahb_sram1/reg_ub_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[15] )
    );
    defparam \cm3inst/ahb_sram1/_i_78/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_77/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [30]),
        .I1(\cm3inst/TARGEXP0HWDATA [14]),
        .I2(\cm3inst/ahb_sram1/reg_ub_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[14] )
    );
    defparam \cm3inst/ahb_sram1/_i_77/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_76/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [29]),
        .I1(\cm3inst/TARGEXP0HWDATA [13]),
        .I2(\cm3inst/ahb_sram1/reg_ub_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[13] )
    );
    defparam \cm3inst/ahb_sram1/_i_76/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_75/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [28]),
        .I1(\cm3inst/TARGEXP0HWDATA [12]),
        .I2(\cm3inst/ahb_sram1/reg_ub_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[12] )
    );
    defparam \cm3inst/ahb_sram1/_i_75/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_74/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [27]),
        .I1(\cm3inst/TARGEXP0HWDATA [11]),
        .I2(\cm3inst/ahb_sram1/reg_ub_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[11] )
    );
    defparam \cm3inst/ahb_sram1/_i_74/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_73/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [26]),
        .I1(\cm3inst/TARGEXP0HWDATA [10]),
        .I2(\cm3inst/ahb_sram1/reg_ub_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[10] )
    );
    defparam \cm3inst/ahb_sram1/_i_73/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_72/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [25]),
        .I1(\cm3inst/TARGEXP0HWDATA [9]),
        .I2(\cm3inst/ahb_sram1/reg_ub_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[9] )
    );
    defparam \cm3inst/ahb_sram1/_i_72/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_71/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [24]),
        .I1(\cm3inst/TARGEXP0HWDATA [8]),
        .I2(\cm3inst/ahb_sram1/reg_ub_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[8] )
    );
    defparam \cm3inst/ahb_sram1/_i_71/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_70/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [23]),
        .I1(\cm3inst/TARGEXP0HWDATA [7]),
        .I2(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[7] )
    );
    defparam \cm3inst/ahb_sram1/_i_70/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_69/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [22]),
        .I1(\cm3inst/TARGEXP0HWDATA [6]),
        .I2(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[6] )
    );
    defparam \cm3inst/ahb_sram1/_i_69/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_68/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [21]),
        .I1(\cm3inst/TARGEXP0HWDATA [5]),
        .I2(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[5] )
    );
    defparam \cm3inst/ahb_sram1/_i_68/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_67/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [20]),
        .I1(\cm3inst/TARGEXP0HWDATA [4]),
        .I2(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[4] )
    );
    defparam \cm3inst/ahb_sram1/_i_67/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_66/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [19]),
        .I1(\cm3inst/TARGEXP0HWDATA [3]),
        .I2(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[3] )
    );
    defparam \cm3inst/ahb_sram1/_i_66/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_65/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [18]),
        .I1(\cm3inst/TARGEXP0HWDATA [2]),
        .I2(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[2] )
    );
    defparam \cm3inst/ahb_sram1/_i_65/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_64/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [17]),
        .I1(\cm3inst/TARGEXP0HWDATA [1]),
        .I2(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[1] )
    );
    defparam \cm3inst/ahb_sram1/_i_64/_i_0 .INIT = 8'HAC;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_63/_i_0 
    (
        .I0(\cm3inst/TARGEXP0HWDATA [16]),
        .I1(\cm3inst/TARGEXP0HWDATA [0]),
        .I2(\cm3inst/ahb_sram1/reg_lb_mux [1]),
        .O(\cm3inst/ahb_sram1/i_dataout[0] )
    );
    defparam \cm3inst/ahb_sram1/_i_63/_i_0 .INIT = 8'HAC;

    xsINVSA \cm3inst/ahb_sram1/_i_4 
    (
        .I(\key_pin[0]_c ),
        .O(\cm3inst/ahb_sram1/n_53 )
    );
    xsLUTSA2 \led_wf1/_i_8 
    (
        .I0(\led_wf1/cnt [0]),
        .I1(_n_1089),
        .O(\led_wf1/n_11 )
    );
    defparam \led_wf1/_i_8 .INIT = 4'H1;

    xsLUTSA2 \led_wf1/_i_9 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[1] ),
        .O(\led_wf1/n_12 )
    );
    defparam \led_wf1/_i_9 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_10 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[2] ),
        .O(\led_wf1/n_13 )
    );
    defparam \led_wf1/_i_10 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_11 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[3] ),
        .O(\led_wf1/n_14 )
    );
    defparam \led_wf1/_i_11 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_12 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[4] ),
        .O(\led_wf1/n_15 )
    );
    defparam \led_wf1/_i_12 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_13 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[5] ),
        .O(\led_wf1/n_16 )
    );
    defparam \led_wf1/_i_13 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_14 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[6] ),
        .O(\led_wf1/n_17 )
    );
    defparam \led_wf1/_i_14 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_15 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[7] ),
        .O(\led_wf1/n_18 )
    );
    defparam \led_wf1/_i_15 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_16 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[8] ),
        .O(\led_wf1/n_19 )
    );
    defparam \led_wf1/_i_16 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_17 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[9] ),
        .O(\led_wf1/n_20 )
    );
    defparam \led_wf1/_i_17 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_18 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[10] ),
        .O(\led_wf1/n_21 )
    );
    defparam \led_wf1/_i_18 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_19 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[11] ),
        .O(\led_wf1/n_22 )
    );
    defparam \led_wf1/_i_19 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_20 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[12] ),
        .O(\led_wf1/n_23 )
    );
    defparam \led_wf1/_i_20 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_21 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[13] ),
        .O(\led_wf1/n_24 )
    );
    defparam \led_wf1/_i_21 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_22 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[14] ),
        .O(\led_wf1/n_25 )
    );
    defparam \led_wf1/_i_22 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_23 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[15] ),
        .O(\led_wf1/n_26 )
    );
    defparam \led_wf1/_i_23 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_24 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[16] ),
        .O(\led_wf1/n_27 )
    );
    defparam \led_wf1/_i_24 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_25 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[17] ),
        .O(\led_wf1/n_28 )
    );
    defparam \led_wf1/_i_25 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_26 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[18] ),
        .O(\led_wf1/n_29 )
    );
    defparam \led_wf1/_i_26 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_27 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[19] ),
        .O(\led_wf1/n_30 )
    );
    defparam \led_wf1/_i_27 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_28 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[20] ),
        .O(\led_wf1/n_31 )
    );
    defparam \led_wf1/_i_28 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_29 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[21] ),
        .O(\led_wf1/n_32 )
    );
    defparam \led_wf1/_i_29 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_30 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[22] ),
        .O(\led_wf1/n_33 )
    );
    defparam \led_wf1/_i_30 .INIT = 4'H4;

    xsLUTSA2 \led_wf1/_i_31 
    (
        .I0(_n_1089),
        .I1(\led_wf1/n_35[23] ),
        .O(\led_wf1/n_34 )
    );
    defparam \led_wf1/_i_31 .INIT = 4'H4;

    xsLUTSA6 \inverted_led_wf1/_i_2/_i_0 
    (
        .I0(\led_wf1/cnt [23]),
        .I1(\led_wf1/cnt [22]),
        .I2(\led_wf1/cnt [21]),
        .I3(\led_wf1/cnt [20]),
        .I4(_n_1090),
        .I5(\led_wf1/_i_2/_i_0_rkd_16 ),
        .O(_n_1089)
    );
    defparam \inverted_led_wf1/_i_2/_i_0 .INIT = 64'H0000001000000000;

    xsLUTSA4 \led_wf1/_i_2/_i_0_rkd_16:0 
    (
        .I0(\led_wf1/cnt [19]),
        .I1(\led_wf1/cnt [18]),
        .I2(\led_wf1/cnt [17]),
        .I3(\led_wf1/cnt [16]),
        .O(\led_wf1/_i_2/_i_0_rkd_16 )
    );
    defparam \led_wf1/_i_2/_i_0_rkd_16:0 .INIT = 16'H0040;

    xsLUTSA6 \dec_of_inverted_led_wf1/_i_2/_i_0 
    (
        .I0(\led_wf1/cnt [7]),
        .I1(\led_wf1/cnt [6]),
        .I2(\led_wf1/cnt [5]),
        .I3(\led_wf1/cnt [4]),
        .I4(\led_wf1/_i_2/_i_0_rkd_12 ),
        .I5(\led_wf1/_i_2/_i_0_rkd_19 ),
        .O(_n_1090)
    );
    defparam \dec_of_inverted_led_wf1/_i_2/_i_0 .INIT = 64'HFFFFFFFFFDFFFFFF;

    xsLUTSA5 \led_wf1/_i_2/_i_0_rkd_19:0 
    (
        .I0(\led_wf1/cnt [15]),
        .I1(\led_wf1/cnt [14]),
        .I2(\led_wf1/cnt [13]),
        .I3(\led_wf1/cnt [12]),
        .I4(\led_wf1/_i_2/_i_0_rkd_14 ),
        .O(\led_wf1/_i_2/_i_0_rkd_19 )
    );
    defparam \led_wf1/_i_2/_i_0_rkd_19:0 .INIT = 32'HFFEFFFFF;

    xsLUTSA4 \led_wf1/_i_2/_i_0_rkd_14:0 
    (
        .I0(\led_wf1/cnt [11]),
        .I1(\led_wf1/cnt [10]),
        .I2(\led_wf1/cnt [9]),
        .I3(\led_wf1/cnt [8]),
        .O(\led_wf1/_i_2/_i_0_rkd_14 )
    );
    defparam \led_wf1/_i_2/_i_0_rkd_14:0 .INIT = 16'H0400;

    xsLUTSA4 \led_wf1/_i_2/_i_0_rkd_12:0 
    (
        .I0(\led_wf1/cnt [3]),
        .I1(\led_wf1/cnt [2]),
        .I2(\led_wf1/cnt [1]),
        .I3(\led_wf1/cnt [0]),
        .O(\led_wf1/_i_2/_i_0_rkd_12 )
    );
    defparam \led_wf1/_i_2/_i_0_rkd_12:0 .INIT = 16'H8000;

    xsINVSA \led_wf1/_i_0 
    (
        .I(\key_pin[1]_c ),
        .O(\led_wf1/n_3 )
    );
    xsLUTSA5 \cm3inst/ahb_sram1/_i_30 
    (
        .I0(\cm3inst/ahb_sram1/reg_active ),
        .I1(\cm3inst/ahb_sram1/n_198 ),
        .I2(\cm3inst/ahb_sram1/n_162 ),
        .I3(\cm3inst/ahb_sram1/n_201 ),
        .I4(\cm3inst/ahb_sram1/n_97 ),
        .O(\cm3inst/TARGEXP0HREADYOUT )
    );
    defparam \cm3inst/ahb_sram1/_i_30 .INIT = 32'H55D555F5;

    xsLUTSA5 \cm3inst/ahb_sram1/_i_38 
    (
        .I0(\cm3inst/ahb_sram1/n_198 ),
        .I1(\cm3inst/ahb_sram1/n_201 ),
        .I2(\cm3inst/ahb_sram1/reg_mcount [2]),
        .I3(\cm3inst/ahb_sram1/reg_mcount [1]),
        .I4(\cm3inst/ahb_sram1/reg_mcount [0]),
        .O(\cm3inst/ahb_sram1/DONE )
    );
    defparam \cm3inst/ahb_sram1/_i_38 .INIT = 32'H22222223;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_31/_i_0 
    (
        .I0(\cm3inst/ahb_sram1/reg_mcount [2]),
        .I1(\cm3inst/ahb_sram1/reg_mcount [1]),
        .I2(\cm3inst/ahb_sram1/reg_mcount [0]),
        .O(\cm3inst/ahb_sram1/n_97 )
    );
    defparam \cm3inst/ahb_sram1/_i_31/_i_0 .INIT = 8'HFE;

    xsLUTSA2 \cm3inst/ahb_sram1/_i_174 
    (
        .I0(\cm3inst/ahb_sram1/n_198 ),
        .I1(\cm3inst/ahb_sram1/n_201 ),
        .O(\cm3inst/ahb_sram1/n_119 )
    );
    defparam \cm3inst/ahb_sram1/_i_174 .INIT = 4'H2;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_233/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_0 [0]),
        .I2(_n_1134_combout),
        .O(\cm3inst/TARGEXP0HRDATA[0] )
    );
    defparam \cm3inst/ahb_sram1/_i_233/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_234/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_0 [1]),
        .I2(_n_1133_combout),
        .O(\cm3inst/TARGEXP0HRDATA[1] )
    );
    defparam \cm3inst/ahb_sram1/_i_234/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_235/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_0 [2]),
        .I2(_n_1132_combout),
        .O(\cm3inst/TARGEXP0HRDATA[2] )
    );
    defparam \cm3inst/ahb_sram1/_i_235/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_236/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_0 [3]),
        .I2(_n_1131_combout),
        .O(\cm3inst/TARGEXP0HRDATA[3] )
    );
    defparam \cm3inst/ahb_sram1/_i_236/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_237/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_0 [4]),
        .I2(_n_1130_combout),
        .O(\cm3inst/TARGEXP0HRDATA[4] )
    );
    defparam \cm3inst/ahb_sram1/_i_237/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_238/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_0 [5]),
        .I2(_n_1129_combout),
        .O(\cm3inst/TARGEXP0HRDATA[5] )
    );
    defparam \cm3inst/ahb_sram1/_i_238/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_239/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_0 [6]),
        .I2(_n_1128_combout),
        .O(\cm3inst/TARGEXP0HRDATA[6] )
    );
    defparam \cm3inst/ahb_sram1/_i_239/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_240/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_0 [7]),
        .I2(_n_1127_combout),
        .O(\cm3inst/TARGEXP0HRDATA[7] )
    );
    defparam \cm3inst/ahb_sram1/_i_240/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_241/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_1 [0]),
        .I2(_n_1126_combout),
        .O(\cm3inst/TARGEXP0HRDATA[8] )
    );
    defparam \cm3inst/ahb_sram1/_i_241/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_242/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_1 [1]),
        .I2(_n_1125_combout),
        .O(\cm3inst/TARGEXP0HRDATA[9] )
    );
    defparam \cm3inst/ahb_sram1/_i_242/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_243/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_1 [2]),
        .I2(_n_1124_combout),
        .O(\cm3inst/TARGEXP0HRDATA[10] )
    );
    defparam \cm3inst/ahb_sram1/_i_243/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_244/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_1 [3]),
        .I2(_n_1123_combout),
        .O(\cm3inst/TARGEXP0HRDATA[11] )
    );
    defparam \cm3inst/ahb_sram1/_i_244/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_245/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_1 [4]),
        .I2(_n_1122_combout),
        .O(\cm3inst/TARGEXP0HRDATA[12] )
    );
    defparam \cm3inst/ahb_sram1/_i_245/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_246/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_1 [5]),
        .I2(_n_1121_combout),
        .O(\cm3inst/TARGEXP0HRDATA[13] )
    );
    defparam \cm3inst/ahb_sram1/_i_246/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_247/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_1 [6]),
        .I2(_n_1120_combout),
        .O(\cm3inst/TARGEXP0HRDATA[14] )
    );
    defparam \cm3inst/ahb_sram1/_i_247/_i_5 .INIT = 8'HD8;

    xsLUTSA3 \cm3inst/ahb_sram1/_i_248/_i_5 
    (
        .I0(\cm3inst/ahb_sram1/reg_size [1]),
        .I1(\cm3inst/ahb_sram1/read_buffer_1 [7]),
        .I2(_n_1119_combout),
        .O(\cm3inst/TARGEXP0HRDATA[15] )
    );
    defparam \cm3inst/ahb_sram1/_i_248/_i_5 .INIT = 8'HD8;

    xs0 _i_3
    (
        .G(n_GND_c)
    );
    xs1 _i_4
    (
        .P(n_VCC_c)
    );


endmodule
